// Code generated by ent, DO NOT EDIT.

package dkimkey

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/zephyraoss/haitatsu/internal/database/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldContainsFold(FieldID, id))
}

// Domain applies equality check predicate on the "domain" field. It's identical to DomainEQ.
func Domain(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldEQ(FieldDomain, v))
}

// Selector applies equality check predicate on the "selector" field. It's identical to SelectorEQ.
func Selector(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldEQ(FieldSelector, v))
}

// PrivateKeyPem applies equality check predicate on the "private_key_pem" field. It's identical to PrivateKeyPemEQ.
func PrivateKeyPem(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldEQ(FieldPrivateKeyPem, v))
}

// PublicKeyPem applies equality check predicate on the "public_key_pem" field. It's identical to PublicKeyPemEQ.
func PublicKeyPem(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldEQ(FieldPublicKeyPem, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldEQ(FieldUpdatedAt, v))
}

// DomainEQ applies the EQ predicate on the "domain" field.
func DomainEQ(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldEQ(FieldDomain, v))
}

// DomainNEQ applies the NEQ predicate on the "domain" field.
func DomainNEQ(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldNEQ(FieldDomain, v))
}

// DomainIn applies the In predicate on the "domain" field.
func DomainIn(vs ...string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldIn(FieldDomain, vs...))
}

// DomainNotIn applies the NotIn predicate on the "domain" field.
func DomainNotIn(vs ...string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldNotIn(FieldDomain, vs...))
}

// DomainGT applies the GT predicate on the "domain" field.
func DomainGT(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldGT(FieldDomain, v))
}

// DomainGTE applies the GTE predicate on the "domain" field.
func DomainGTE(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldGTE(FieldDomain, v))
}

// DomainLT applies the LT predicate on the "domain" field.
func DomainLT(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldLT(FieldDomain, v))
}

// DomainLTE applies the LTE predicate on the "domain" field.
func DomainLTE(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldLTE(FieldDomain, v))
}

// DomainContains applies the Contains predicate on the "domain" field.
func DomainContains(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldContains(FieldDomain, v))
}

// DomainHasPrefix applies the HasPrefix predicate on the "domain" field.
func DomainHasPrefix(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldHasPrefix(FieldDomain, v))
}

// DomainHasSuffix applies the HasSuffix predicate on the "domain" field.
func DomainHasSuffix(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldHasSuffix(FieldDomain, v))
}

// DomainEqualFold applies the EqualFold predicate on the "domain" field.
func DomainEqualFold(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldEqualFold(FieldDomain, v))
}

// DomainContainsFold applies the ContainsFold predicate on the "domain" field.
func DomainContainsFold(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldContainsFold(FieldDomain, v))
}

// SelectorEQ applies the EQ predicate on the "selector" field.
func SelectorEQ(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldEQ(FieldSelector, v))
}

// SelectorNEQ applies the NEQ predicate on the "selector" field.
func SelectorNEQ(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldNEQ(FieldSelector, v))
}

// SelectorIn applies the In predicate on the "selector" field.
func SelectorIn(vs ...string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldIn(FieldSelector, vs...))
}

// SelectorNotIn applies the NotIn predicate on the "selector" field.
func SelectorNotIn(vs ...string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldNotIn(FieldSelector, vs...))
}

// SelectorGT applies the GT predicate on the "selector" field.
func SelectorGT(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldGT(FieldSelector, v))
}

// SelectorGTE applies the GTE predicate on the "selector" field.
func SelectorGTE(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldGTE(FieldSelector, v))
}

// SelectorLT applies the LT predicate on the "selector" field.
func SelectorLT(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldLT(FieldSelector, v))
}

// SelectorLTE applies the LTE predicate on the "selector" field.
func SelectorLTE(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldLTE(FieldSelector, v))
}

// SelectorContains applies the Contains predicate on the "selector" field.
func SelectorContains(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldContains(FieldSelector, v))
}

// SelectorHasPrefix applies the HasPrefix predicate on the "selector" field.
func SelectorHasPrefix(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldHasPrefix(FieldSelector, v))
}

// SelectorHasSuffix applies the HasSuffix predicate on the "selector" field.
func SelectorHasSuffix(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldHasSuffix(FieldSelector, v))
}

// SelectorEqualFold applies the EqualFold predicate on the "selector" field.
func SelectorEqualFold(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldEqualFold(FieldSelector, v))
}

// SelectorContainsFold applies the ContainsFold predicate on the "selector" field.
func SelectorContainsFold(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldContainsFold(FieldSelector, v))
}

// PrivateKeyPemEQ applies the EQ predicate on the "private_key_pem" field.
func PrivateKeyPemEQ(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldEQ(FieldPrivateKeyPem, v))
}

// PrivateKeyPemNEQ applies the NEQ predicate on the "private_key_pem" field.
func PrivateKeyPemNEQ(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldNEQ(FieldPrivateKeyPem, v))
}

// PrivateKeyPemIn applies the In predicate on the "private_key_pem" field.
func PrivateKeyPemIn(vs ...string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldIn(FieldPrivateKeyPem, vs...))
}

// PrivateKeyPemNotIn applies the NotIn predicate on the "private_key_pem" field.
func PrivateKeyPemNotIn(vs ...string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldNotIn(FieldPrivateKeyPem, vs...))
}

// PrivateKeyPemGT applies the GT predicate on the "private_key_pem" field.
func PrivateKeyPemGT(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldGT(FieldPrivateKeyPem, v))
}

// PrivateKeyPemGTE applies the GTE predicate on the "private_key_pem" field.
func PrivateKeyPemGTE(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldGTE(FieldPrivateKeyPem, v))
}

// PrivateKeyPemLT applies the LT predicate on the "private_key_pem" field.
func PrivateKeyPemLT(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldLT(FieldPrivateKeyPem, v))
}

// PrivateKeyPemLTE applies the LTE predicate on the "private_key_pem" field.
func PrivateKeyPemLTE(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldLTE(FieldPrivateKeyPem, v))
}

// PrivateKeyPemContains applies the Contains predicate on the "private_key_pem" field.
func PrivateKeyPemContains(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldContains(FieldPrivateKeyPem, v))
}

// PrivateKeyPemHasPrefix applies the HasPrefix predicate on the "private_key_pem" field.
func PrivateKeyPemHasPrefix(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldHasPrefix(FieldPrivateKeyPem, v))
}

// PrivateKeyPemHasSuffix applies the HasSuffix predicate on the "private_key_pem" field.
func PrivateKeyPemHasSuffix(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldHasSuffix(FieldPrivateKeyPem, v))
}

// PrivateKeyPemEqualFold applies the EqualFold predicate on the "private_key_pem" field.
func PrivateKeyPemEqualFold(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldEqualFold(FieldPrivateKeyPem, v))
}

// PrivateKeyPemContainsFold applies the ContainsFold predicate on the "private_key_pem" field.
func PrivateKeyPemContainsFold(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldContainsFold(FieldPrivateKeyPem, v))
}

// PublicKeyPemEQ applies the EQ predicate on the "public_key_pem" field.
func PublicKeyPemEQ(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldEQ(FieldPublicKeyPem, v))
}

// PublicKeyPemNEQ applies the NEQ predicate on the "public_key_pem" field.
func PublicKeyPemNEQ(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldNEQ(FieldPublicKeyPem, v))
}

// PublicKeyPemIn applies the In predicate on the "public_key_pem" field.
func PublicKeyPemIn(vs ...string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldIn(FieldPublicKeyPem, vs...))
}

// PublicKeyPemNotIn applies the NotIn predicate on the "public_key_pem" field.
func PublicKeyPemNotIn(vs ...string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldNotIn(FieldPublicKeyPem, vs...))
}

// PublicKeyPemGT applies the GT predicate on the "public_key_pem" field.
func PublicKeyPemGT(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldGT(FieldPublicKeyPem, v))
}

// PublicKeyPemGTE applies the GTE predicate on the "public_key_pem" field.
func PublicKeyPemGTE(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldGTE(FieldPublicKeyPem, v))
}

// PublicKeyPemLT applies the LT predicate on the "public_key_pem" field.
func PublicKeyPemLT(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldLT(FieldPublicKeyPem, v))
}

// PublicKeyPemLTE applies the LTE predicate on the "public_key_pem" field.
func PublicKeyPemLTE(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldLTE(FieldPublicKeyPem, v))
}

// PublicKeyPemContains applies the Contains predicate on the "public_key_pem" field.
func PublicKeyPemContains(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldContains(FieldPublicKeyPem, v))
}

// PublicKeyPemHasPrefix applies the HasPrefix predicate on the "public_key_pem" field.
func PublicKeyPemHasPrefix(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldHasPrefix(FieldPublicKeyPem, v))
}

// PublicKeyPemHasSuffix applies the HasSuffix predicate on the "public_key_pem" field.
func PublicKeyPemHasSuffix(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldHasSuffix(FieldPublicKeyPem, v))
}

// PublicKeyPemEqualFold applies the EqualFold predicate on the "public_key_pem" field.
func PublicKeyPemEqualFold(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldEqualFold(FieldPublicKeyPem, v))
}

// PublicKeyPemContainsFold applies the ContainsFold predicate on the "public_key_pem" field.
func PublicKeyPemContainsFold(v string) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldContainsFold(FieldPublicKeyPem, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DKIMKey {
	return predicate.DKIMKey(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DKIMKey) predicate.DKIMKey {
	return predicate.DKIMKey(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DKIMKey) predicate.DKIMKey {
	return predicate.DKIMKey(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DKIMKey) predicate.DKIMKey {
	return predicate.DKIMKey(sql.NotPredicates(p))
}
