// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AppPassword is the predicate function for apppassword builders.
type AppPassword func(*sql.Selector)

// AuditEvent is the predicate function for auditevent builders.
type AuditEvent func(*sql.Selector)

// Folder is the predicate function for folder builders.
type Folder func(*sql.Selector)

// Label is the predicate function for label builders.
type Label func(*sql.Selector)

// Mailbox is the predicate function for mailbox builders.
type Mailbox func(*sql.Selector)

// MailboxMessage is the predicate function for mailboxmessage builders.
type MailboxMessage func(*sql.Selector)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)

// Route is the predicate function for route builders.
type Route func(*sql.Selector)

// RoutingRule is the predicate function for routingrule builders.
type RoutingRule func(*sql.Selector)
