// Code generated by ent, DO NOT EDIT.

package exportjob

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/zephyraoss/haitatsu/internal/database/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldContainsFold(FieldID, id))
}

// MailboxID applies equality check predicate on the "mailbox_id" field. It's identical to MailboxIDEQ.
func MailboxID(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldEQ(FieldMailboxID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldEQ(FieldStatus, v))
}

// ObjectKey applies equality check predicate on the "object_key" field. It's identical to ObjectKeyEQ.
func ObjectKey(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldEQ(FieldObjectKey, v))
}

// SizeBytes applies equality check predicate on the "size_bytes" field. It's identical to SizeBytesEQ.
func SizeBytes(v int64) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldEQ(FieldSizeBytes, v))
}

// LockedBy applies equality check predicate on the "locked_by" field. It's identical to LockedByEQ.
func LockedBy(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldEQ(FieldLockedBy, v))
}

// LockedUntil applies equality check predicate on the "locked_until" field. It's identical to LockedUntilEQ.
func LockedUntil(v time.Time) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldEQ(FieldLockedUntil, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// MailboxIDEQ applies the EQ predicate on the "mailbox_id" field.
func MailboxIDEQ(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldEQ(FieldMailboxID, v))
}

// MailboxIDNEQ applies the NEQ predicate on the "mailbox_id" field.
func MailboxIDNEQ(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldNEQ(FieldMailboxID, v))
}

// MailboxIDIn applies the In predicate on the "mailbox_id" field.
func MailboxIDIn(vs ...string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldIn(FieldMailboxID, vs...))
}

// MailboxIDNotIn applies the NotIn predicate on the "mailbox_id" field.
func MailboxIDNotIn(vs ...string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldNotIn(FieldMailboxID, vs...))
}

// MailboxIDGT applies the GT predicate on the "mailbox_id" field.
func MailboxIDGT(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldGT(FieldMailboxID, v))
}

// MailboxIDGTE applies the GTE predicate on the "mailbox_id" field.
func MailboxIDGTE(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldGTE(FieldMailboxID, v))
}

// MailboxIDLT applies the LT predicate on the "mailbox_id" field.
func MailboxIDLT(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldLT(FieldMailboxID, v))
}

// MailboxIDLTE applies the LTE predicate on the "mailbox_id" field.
func MailboxIDLTE(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldLTE(FieldMailboxID, v))
}

// MailboxIDContains applies the Contains predicate on the "mailbox_id" field.
func MailboxIDContains(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldContains(FieldMailboxID, v))
}

// MailboxIDHasPrefix applies the HasPrefix predicate on the "mailbox_id" field.
func MailboxIDHasPrefix(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldHasPrefix(FieldMailboxID, v))
}

// MailboxIDHasSuffix applies the HasSuffix predicate on the "mailbox_id" field.
func MailboxIDHasSuffix(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldHasSuffix(FieldMailboxID, v))
}

// MailboxIDEqualFold applies the EqualFold predicate on the "mailbox_id" field.
func MailboxIDEqualFold(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldEqualFold(FieldMailboxID, v))
}

// MailboxIDContainsFold applies the ContainsFold predicate on the "mailbox_id" field.
func MailboxIDContainsFold(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldContainsFold(FieldMailboxID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldContainsFold(FieldStatus, v))
}

// ObjectKeyEQ applies the EQ predicate on the "object_key" field.
func ObjectKeyEQ(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldEQ(FieldObjectKey, v))
}

// ObjectKeyNEQ applies the NEQ predicate on the "object_key" field.
func ObjectKeyNEQ(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldNEQ(FieldObjectKey, v))
}

// ObjectKeyIn applies the In predicate on the "object_key" field.
func ObjectKeyIn(vs ...string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldIn(FieldObjectKey, vs...))
}

// ObjectKeyNotIn applies the NotIn predicate on the "object_key" field.
func ObjectKeyNotIn(vs ...string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldNotIn(FieldObjectKey, vs...))
}

// ObjectKeyGT applies the GT predicate on the "object_key" field.
func ObjectKeyGT(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldGT(FieldObjectKey, v))
}

// ObjectKeyGTE applies the GTE predicate on the "object_key" field.
func ObjectKeyGTE(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldGTE(FieldObjectKey, v))
}

// ObjectKeyLT applies the LT predicate on the "object_key" field.
func ObjectKeyLT(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldLT(FieldObjectKey, v))
}

// ObjectKeyLTE applies the LTE predicate on the "object_key" field.
func ObjectKeyLTE(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldLTE(FieldObjectKey, v))
}

// ObjectKeyContains applies the Contains predicate on the "object_key" field.
func ObjectKeyContains(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldContains(FieldObjectKey, v))
}

// ObjectKeyHasPrefix applies the HasPrefix predicate on the "object_key" field.
func ObjectKeyHasPrefix(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldHasPrefix(FieldObjectKey, v))
}

// ObjectKeyHasSuffix applies the HasSuffix predicate on the "object_key" field.
func ObjectKeyHasSuffix(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldHasSuffix(FieldObjectKey, v))
}

// ObjectKeyIsNil applies the IsNil predicate on the "object_key" field.
func ObjectKeyIsNil() predicate.ExportJob {
	return predicate.ExportJob(sql.FieldIsNull(FieldObjectKey))
}

// ObjectKeyNotNil applies the NotNil predicate on the "object_key" field.
func ObjectKeyNotNil() predicate.ExportJob {
	return predicate.ExportJob(sql.FieldNotNull(FieldObjectKey))
}

// ObjectKeyEqualFold applies the EqualFold predicate on the "object_key" field.
func ObjectKeyEqualFold(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldEqualFold(FieldObjectKey, v))
}

// ObjectKeyContainsFold applies the ContainsFold predicate on the "object_key" field.
func ObjectKeyContainsFold(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldContainsFold(FieldObjectKey, v))
}

// SizeBytesEQ applies the EQ predicate on the "size_bytes" field.
func SizeBytesEQ(v int64) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldEQ(FieldSizeBytes, v))
}

// SizeBytesNEQ applies the NEQ predicate on the "size_bytes" field.
func SizeBytesNEQ(v int64) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldNEQ(FieldSizeBytes, v))
}

// SizeBytesIn applies the In predicate on the "size_bytes" field.
func SizeBytesIn(vs ...int64) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldIn(FieldSizeBytes, vs...))
}

// SizeBytesNotIn applies the NotIn predicate on the "size_bytes" field.
func SizeBytesNotIn(vs ...int64) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldNotIn(FieldSizeBytes, vs...))
}

// SizeBytesGT applies the GT predicate on the "size_bytes" field.
func SizeBytesGT(v int64) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldGT(FieldSizeBytes, v))
}

// SizeBytesGTE applies the GTE predicate on the "size_bytes" field.
func SizeBytesGTE(v int64) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldGTE(FieldSizeBytes, v))
}

// SizeBytesLT applies the LT predicate on the "size_bytes" field.
func SizeBytesLT(v int64) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldLT(FieldSizeBytes, v))
}

// SizeBytesLTE applies the LTE predicate on the "size_bytes" field.
func SizeBytesLTE(v int64) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldLTE(FieldSizeBytes, v))
}

// LockedByEQ applies the EQ predicate on the "locked_by" field.
func LockedByEQ(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldEQ(FieldLockedBy, v))
}

// LockedByNEQ applies the NEQ predicate on the "locked_by" field.
func LockedByNEQ(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldNEQ(FieldLockedBy, v))
}

// LockedByIn applies the In predicate on the "locked_by" field.
func LockedByIn(vs ...string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldIn(FieldLockedBy, vs...))
}

// LockedByNotIn applies the NotIn predicate on the "locked_by" field.
func LockedByNotIn(vs ...string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldNotIn(FieldLockedBy, vs...))
}

// LockedByGT applies the GT predicate on the "locked_by" field.
func LockedByGT(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldGT(FieldLockedBy, v))
}

// LockedByGTE applies the GTE predicate on the "locked_by" field.
func LockedByGTE(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldGTE(FieldLockedBy, v))
}

// LockedByLT applies the LT predicate on the "locked_by" field.
func LockedByLT(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldLT(FieldLockedBy, v))
}

// LockedByLTE applies the LTE predicate on the "locked_by" field.
func LockedByLTE(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldLTE(FieldLockedBy, v))
}

// LockedByContains applies the Contains predicate on the "locked_by" field.
func LockedByContains(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldContains(FieldLockedBy, v))
}

// LockedByHasPrefix applies the HasPrefix predicate on the "locked_by" field.
func LockedByHasPrefix(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldHasPrefix(FieldLockedBy, v))
}

// LockedByHasSuffix applies the HasSuffix predicate on the "locked_by" field.
func LockedByHasSuffix(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldHasSuffix(FieldLockedBy, v))
}

// LockedByIsNil applies the IsNil predicate on the "locked_by" field.
func LockedByIsNil() predicate.ExportJob {
	return predicate.ExportJob(sql.FieldIsNull(FieldLockedBy))
}

// LockedByNotNil applies the NotNil predicate on the "locked_by" field.
func LockedByNotNil() predicate.ExportJob {
	return predicate.ExportJob(sql.FieldNotNull(FieldLockedBy))
}

// LockedByEqualFold applies the EqualFold predicate on the "locked_by" field.
func LockedByEqualFold(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldEqualFold(FieldLockedBy, v))
}

// LockedByContainsFold applies the ContainsFold predicate on the "locked_by" field.
func LockedByContainsFold(v string) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldContainsFold(FieldLockedBy, v))
}

// LockedUntilEQ applies the EQ predicate on the "locked_until" field.
func LockedUntilEQ(v time.Time) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldEQ(FieldLockedUntil, v))
}

// LockedUntilNEQ applies the NEQ predicate on the "locked_until" field.
func LockedUntilNEQ(v time.Time) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldNEQ(FieldLockedUntil, v))
}

// LockedUntilIn applies the In predicate on the "locked_until" field.
func LockedUntilIn(vs ...time.Time) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldIn(FieldLockedUntil, vs...))
}

// LockedUntilNotIn applies the NotIn predicate on the "locked_until" field.
func LockedUntilNotIn(vs ...time.Time) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldNotIn(FieldLockedUntil, vs...))
}

// LockedUntilGT applies the GT predicate on the "locked_until" field.
func LockedUntilGT(v time.Time) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldGT(FieldLockedUntil, v))
}

// LockedUntilGTE applies the GTE predicate on the "locked_until" field.
func LockedUntilGTE(v time.Time) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldGTE(FieldLockedUntil, v))
}

// LockedUntilLT applies the LT predicate on the "locked_until" field.
func LockedUntilLT(v time.Time) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldLT(FieldLockedUntil, v))
}

// LockedUntilLTE applies the LTE predicate on the "locked_until" field.
func LockedUntilLTE(v time.Time) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldLTE(FieldLockedUntil, v))
}

// LockedUntilIsNil applies the IsNil predicate on the "locked_until" field.
func LockedUntilIsNil() predicate.ExportJob {
	return predicate.ExportJob(sql.FieldIsNull(FieldLockedUntil))
}

// LockedUntilNotNil applies the NotNil predicate on the "locked_until" field.
func LockedUntilNotNil() predicate.ExportJob {
	return predicate.ExportJob(sql.FieldNotNull(FieldLockedUntil))
}

// LastErrorIsNil applies the IsNil predicate on the "last_error" field.
func LastErrorIsNil() predicate.ExportJob {
	return predicate.ExportJob(sql.FieldIsNull(FieldLastError))
}

// LastErrorNotNil applies the NotNil predicate on the "last_error" field.
func LastErrorNotNil() predicate.ExportJob {
	return predicate.ExportJob(sql.FieldNotNull(FieldLastError))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.ExportJob {
	return predicate.ExportJob(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.ExportJob {
	return predicate.ExportJob(sql.FieldNotNull(FieldExpiresAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ExportJob {
	return predicate.ExportJob(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ExportJob) predicate.ExportJob {
	return predicate.ExportJob(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ExportJob) predicate.ExportJob {
	return predicate.ExportJob(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ExportJob) predicate.ExportJob {
	return predicate.ExportJob(sql.NotPredicates(p))
}
