// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/zephyraoss/haitatsu/internal/database/ent/apppassword"
	"github.com/zephyraoss/haitatsu/internal/database/ent/predicate"
)

// AppPasswordUpdate is the builder for updating AppPassword entities.
type AppPasswordUpdate struct {
	config
	hooks    []Hook
	mutation *AppPasswordMutation
}

// Where appends a list predicates to the AppPasswordUpdate builder.
func (_u *AppPasswordUpdate) Where(ps ...predicate.AppPassword) *AppPasswordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMailboxID sets the "mailbox_id" field.
func (_u *AppPasswordUpdate) SetMailboxID(v string) *AppPasswordUpdate {
	_u.mutation.SetMailboxID(v)
	return _u
}

// SetNillableMailboxID sets the "mailbox_id" field if the given value is not nil.
func (_u *AppPasswordUpdate) SetNillableMailboxID(v *string) *AppPasswordUpdate {
	if v != nil {
		_u.SetMailboxID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *AppPasswordUpdate) SetName(v string) *AppPasswordUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AppPasswordUpdate) SetNillableName(v *string) *AppPasswordUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetHash sets the "hash" field.
func (_u *AppPasswordUpdate) SetHash(v string) *AppPasswordUpdate {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *AppPasswordUpdate) SetNillableHash(v *string) *AppPasswordUpdate {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *AppPasswordUpdate) SetScopes(v []string) *AppPasswordUpdate {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *AppPasswordUpdate) AppendScopes(v []string) *AppPasswordUpdate {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *AppPasswordUpdate) SetLastUsedAt(v time.Time) *AppPasswordUpdate {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *AppPasswordUpdate) SetNillableLastUsedAt(v *time.Time) *AppPasswordUpdate {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *AppPasswordUpdate) ClearLastUsedAt() *AppPasswordUpdate {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *AppPasswordUpdate) SetRevokedAt(v time.Time) *AppPasswordUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *AppPasswordUpdate) SetNillableRevokedAt(v *time.Time) *AppPasswordUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *AppPasswordUpdate) ClearRevokedAt() *AppPasswordUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AppPasswordUpdate) SetUpdatedAt(v time.Time) *AppPasswordUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AppPasswordUpdate) SetDeletedAt(v time.Time) *AppPasswordUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AppPasswordUpdate) SetNillableDeletedAt(v *time.Time) *AppPasswordUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AppPasswordUpdate) ClearDeletedAt() *AppPasswordUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// Mutation returns the AppPasswordMutation object of the builder.
func (_u *AppPasswordUpdate) Mutation() *AppPasswordMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AppPasswordUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AppPasswordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AppPasswordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AppPasswordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AppPasswordUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := apppassword.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *AppPasswordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(apppassword.Table, apppassword.Columns, sqlgraph.NewFieldSpec(apppassword.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MailboxID(); ok {
		_spec.SetField(apppassword.FieldMailboxID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(apppassword.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(apppassword.FieldHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(apppassword.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, apppassword.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(apppassword.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(apppassword.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(apppassword.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(apppassword.FieldRevokedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(apppassword.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(apppassword.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(apppassword.FieldDeletedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apppassword.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AppPasswordUpdateOne is the builder for updating a single AppPassword entity.
type AppPasswordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AppPasswordMutation
}

// SetMailboxID sets the "mailbox_id" field.
func (_u *AppPasswordUpdateOne) SetMailboxID(v string) *AppPasswordUpdateOne {
	_u.mutation.SetMailboxID(v)
	return _u
}

// SetNillableMailboxID sets the "mailbox_id" field if the given value is not nil.
func (_u *AppPasswordUpdateOne) SetNillableMailboxID(v *string) *AppPasswordUpdateOne {
	if v != nil {
		_u.SetMailboxID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *AppPasswordUpdateOne) SetName(v string) *AppPasswordUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AppPasswordUpdateOne) SetNillableName(v *string) *AppPasswordUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetHash sets the "hash" field.
func (_u *AppPasswordUpdateOne) SetHash(v string) *AppPasswordUpdateOne {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *AppPasswordUpdateOne) SetNillableHash(v *string) *AppPasswordUpdateOne {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *AppPasswordUpdateOne) SetScopes(v []string) *AppPasswordUpdateOne {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *AppPasswordUpdateOne) AppendScopes(v []string) *AppPasswordUpdateOne {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *AppPasswordUpdateOne) SetLastUsedAt(v time.Time) *AppPasswordUpdateOne {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *AppPasswordUpdateOne) SetNillableLastUsedAt(v *time.Time) *AppPasswordUpdateOne {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *AppPasswordUpdateOne) ClearLastUsedAt() *AppPasswordUpdateOne {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *AppPasswordUpdateOne) SetRevokedAt(v time.Time) *AppPasswordUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *AppPasswordUpdateOne) SetNillableRevokedAt(v *time.Time) *AppPasswordUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *AppPasswordUpdateOne) ClearRevokedAt() *AppPasswordUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AppPasswordUpdateOne) SetUpdatedAt(v time.Time) *AppPasswordUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AppPasswordUpdateOne) SetDeletedAt(v time.Time) *AppPasswordUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AppPasswordUpdateOne) SetNillableDeletedAt(v *time.Time) *AppPasswordUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AppPasswordUpdateOne) ClearDeletedAt() *AppPasswordUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// Mutation returns the AppPasswordMutation object of the builder.
func (_u *AppPasswordUpdateOne) Mutation() *AppPasswordMutation {
	return _u.mutation
}

// Where appends a list predicates to the AppPasswordUpdate builder.
func (_u *AppPasswordUpdateOne) Where(ps ...predicate.AppPassword) *AppPasswordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AppPasswordUpdateOne) Select(field string, fields ...string) *AppPasswordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AppPassword entity.
func (_u *AppPasswordUpdateOne) Save(ctx context.Context) (*AppPassword, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AppPasswordUpdateOne) SaveX(ctx context.Context) *AppPassword {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AppPasswordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AppPasswordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AppPasswordUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := apppassword.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *AppPasswordUpdateOne) sqlSave(ctx context.Context) (_node *AppPassword, err error) {
	_spec := sqlgraph.NewUpdateSpec(apppassword.Table, apppassword.Columns, sqlgraph.NewFieldSpec(apppassword.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AppPassword.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apppassword.FieldID)
		for _, f := range fields {
			if !apppassword.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != apppassword.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MailboxID(); ok {
		_spec.SetField(apppassword.FieldMailboxID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(apppassword.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(apppassword.FieldHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(apppassword.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, apppassword.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(apppassword.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(apppassword.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(apppassword.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(apppassword.FieldRevokedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(apppassword.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(apppassword.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(apppassword.FieldDeletedAt, field.TypeTime)
	}
	_node = &AppPassword{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apppassword.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
