// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zephyraoss/haitatsu/internal/database/ent/bounceevent"
	"github.com/zephyraoss/haitatsu/internal/database/ent/predicate"
)

// BounceEventUpdate is the builder for updating BounceEvent entities.
type BounceEventUpdate struct {
	config
	hooks    []Hook
	mutation *BounceEventMutation
}

// Where appends a list predicates to the BounceEventUpdate builder.
func (_u *BounceEventUpdate) Where(ps ...predicate.BounceEvent) *BounceEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *BounceEventUpdate) SetMessageID(v string) *BounceEventUpdate {
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *BounceEventUpdate) SetNillableMessageID(v *string) *BounceEventUpdate {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// SetRecipient sets the "recipient" field.
func (_u *BounceEventUpdate) SetRecipient(v string) *BounceEventUpdate {
	_u.mutation.SetRecipient(v)
	return _u
}

// SetNillableRecipient sets the "recipient" field if the given value is not nil.
func (_u *BounceEventUpdate) SetNillableRecipient(v *string) *BounceEventUpdate {
	if v != nil {
		_u.SetRecipient(*v)
	}
	return _u
}

// SetBlobKey sets the "blob_key" field.
func (_u *BounceEventUpdate) SetBlobKey(v string) *BounceEventUpdate {
	_u.mutation.SetBlobKey(v)
	return _u
}

// SetNillableBlobKey sets the "blob_key" field if the given value is not nil.
func (_u *BounceEventUpdate) SetNillableBlobKey(v *string) *BounceEventUpdate {
	if v != nil {
		_u.SetBlobKey(*v)
	}
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *BounceEventUpdate) SetSha256(v string) *BounceEventUpdate {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *BounceEventUpdate) SetNillableSha256(v *string) *BounceEventUpdate {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *BounceEventUpdate) SetSizeBytes(v int64) *BounceEventUpdate {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *BounceEventUpdate) SetNillableSizeBytes(v *int64) *BounceEventUpdate {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *BounceEventUpdate) AddSizeBytes(v int64) *BounceEventUpdate {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetDetails sets the "details" field.
func (_u *BounceEventUpdate) SetDetails(v map[string]interface{}) *BounceEventUpdate {
	_u.mutation.SetDetails(v)
	return _u
}

// ClearDetails clears the value of the "details" field.
func (_u *BounceEventUpdate) ClearDetails() *BounceEventUpdate {
	_u.mutation.ClearDetails()
	return _u
}

// Mutation returns the BounceEventMutation object of the builder.
func (_u *BounceEventUpdate) Mutation() *BounceEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BounceEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BounceEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BounceEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BounceEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *BounceEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(bounceevent.Table, bounceevent.Columns, sqlgraph.NewFieldSpec(bounceevent.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(bounceevent.FieldMessageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Recipient(); ok {
		_spec.SetField(bounceevent.FieldRecipient, field.TypeString, value)
	}
	if value, ok := _u.mutation.BlobKey(); ok {
		_spec.SetField(bounceevent.FieldBlobKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(bounceevent.FieldSha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(bounceevent.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(bounceevent.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Details(); ok {
		_spec.SetField(bounceevent.FieldDetails, field.TypeJSON, value)
	}
	if _u.mutation.DetailsCleared() {
		_spec.ClearField(bounceevent.FieldDetails, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bounceevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BounceEventUpdateOne is the builder for updating a single BounceEvent entity.
type BounceEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BounceEventMutation
}

// SetMessageID sets the "message_id" field.
func (_u *BounceEventUpdateOne) SetMessageID(v string) *BounceEventUpdateOne {
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *BounceEventUpdateOne) SetNillableMessageID(v *string) *BounceEventUpdateOne {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// SetRecipient sets the "recipient" field.
func (_u *BounceEventUpdateOne) SetRecipient(v string) *BounceEventUpdateOne {
	_u.mutation.SetRecipient(v)
	return _u
}

// SetNillableRecipient sets the "recipient" field if the given value is not nil.
func (_u *BounceEventUpdateOne) SetNillableRecipient(v *string) *BounceEventUpdateOne {
	if v != nil {
		_u.SetRecipient(*v)
	}
	return _u
}

// SetBlobKey sets the "blob_key" field.
func (_u *BounceEventUpdateOne) SetBlobKey(v string) *BounceEventUpdateOne {
	_u.mutation.SetBlobKey(v)
	return _u
}

// SetNillableBlobKey sets the "blob_key" field if the given value is not nil.
func (_u *BounceEventUpdateOne) SetNillableBlobKey(v *string) *BounceEventUpdateOne {
	if v != nil {
		_u.SetBlobKey(*v)
	}
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *BounceEventUpdateOne) SetSha256(v string) *BounceEventUpdateOne {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *BounceEventUpdateOne) SetNillableSha256(v *string) *BounceEventUpdateOne {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *BounceEventUpdateOne) SetSizeBytes(v int64) *BounceEventUpdateOne {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *BounceEventUpdateOne) SetNillableSizeBytes(v *int64) *BounceEventUpdateOne {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *BounceEventUpdateOne) AddSizeBytes(v int64) *BounceEventUpdateOne {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetDetails sets the "details" field.
func (_u *BounceEventUpdateOne) SetDetails(v map[string]interface{}) *BounceEventUpdateOne {
	_u.mutation.SetDetails(v)
	return _u
}

// ClearDetails clears the value of the "details" field.
func (_u *BounceEventUpdateOne) ClearDetails() *BounceEventUpdateOne {
	_u.mutation.ClearDetails()
	return _u
}

// Mutation returns the BounceEventMutation object of the builder.
func (_u *BounceEventUpdateOne) Mutation() *BounceEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the BounceEventUpdate builder.
func (_u *BounceEventUpdateOne) Where(ps ...predicate.BounceEvent) *BounceEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BounceEventUpdateOne) Select(field string, fields ...string) *BounceEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BounceEvent entity.
func (_u *BounceEventUpdateOne) Save(ctx context.Context) (*BounceEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BounceEventUpdateOne) SaveX(ctx context.Context) *BounceEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BounceEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BounceEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *BounceEventUpdateOne) sqlSave(ctx context.Context) (_node *BounceEvent, err error) {
	_spec := sqlgraph.NewUpdateSpec(bounceevent.Table, bounceevent.Columns, sqlgraph.NewFieldSpec(bounceevent.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BounceEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bounceevent.FieldID)
		for _, f := range fields {
			if !bounceevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != bounceevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(bounceevent.FieldMessageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Recipient(); ok {
		_spec.SetField(bounceevent.FieldRecipient, field.TypeString, value)
	}
	if value, ok := _u.mutation.BlobKey(); ok {
		_spec.SetField(bounceevent.FieldBlobKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(bounceevent.FieldSha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(bounceevent.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(bounceevent.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Details(); ok {
		_spec.SetField(bounceevent.FieldDetails, field.TypeJSON, value)
	}
	if _u.mutation.DetailsCleared() {
		_spec.ClearField(bounceevent.FieldDetails, field.TypeJSON)
	}
	_node = &BounceEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bounceevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
