// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/zephyraoss/haitatsu/internal/database/ent/dkimkey"
)

// DKIMKey is the model entity for the DKIMKey schema.
type DKIMKey struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Domain holds the value of the "domain" field.
	Domain string `json:"domain,omitempty"`
	// Selector holds the value of the "selector" field.
	Selector string `json:"selector,omitempty"`
	// PrivateKeyPem holds the value of the "private_key_pem" field.
	PrivateKeyPem string `json:"private_key_pem,omitempty"`
	// PublicKeyPem holds the value of the "public_key_pem" field.
	PublicKeyPem string `json:"public_key_pem,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DKIMKey) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case dkimkey.FieldID, dkimkey.FieldDomain, dkimkey.FieldSelector, dkimkey.FieldPrivateKeyPem, dkimkey.FieldPublicKeyPem:
			values[i] = new(sql.NullString)
		case dkimkey.FieldCreatedAt, dkimkey.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DKIMKey fields.
func (_m *DKIMKey) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dkimkey.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case dkimkey.FieldDomain:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field domain", values[i])
			} else if value.Valid {
				_m.Domain = value.String
			}
		case dkimkey.FieldSelector:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field selector", values[i])
			} else if value.Valid {
				_m.Selector = value.String
			}
		case dkimkey.FieldPrivateKeyPem:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field private_key_pem", values[i])
			} else if value.Valid {
				_m.PrivateKeyPem = value.String
			}
		case dkimkey.FieldPublicKeyPem:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field public_key_pem", values[i])
			} else if value.Valid {
				_m.PublicKeyPem = value.String
			}
		case dkimkey.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case dkimkey.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DKIMKey.
// This includes values selected through modifiers, order, etc.
func (_m *DKIMKey) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this DKIMKey.
// Note that you need to call DKIMKey.Unwrap() before calling this method if this DKIMKey
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DKIMKey) Update() *DKIMKeyUpdateOne {
	return NewDKIMKeyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DKIMKey entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DKIMKey) Unwrap() *DKIMKey {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DKIMKey is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DKIMKey) String() string {
	var builder strings.Builder
	builder.WriteString("DKIMKey(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("domain=")
	builder.WriteString(_m.Domain)
	builder.WriteString(", ")
	builder.WriteString("selector=")
	builder.WriteString(_m.Selector)
	builder.WriteString(", ")
	builder.WriteString("private_key_pem=")
	builder.WriteString(_m.PrivateKeyPem)
	builder.WriteString(", ")
	builder.WriteString("public_key_pem=")
	builder.WriteString(_m.PublicKeyPem)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DKIMKeys is a parsable slice of DKIMKey.
type DKIMKeys []*DKIMKey
