// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zephyraoss/haitatsu/internal/database/ent/dkimkey"
)

// DKIMKeyCreate is the builder for creating a DKIMKey entity.
type DKIMKeyCreate struct {
	config
	mutation *DKIMKeyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetDomain sets the "domain" field.
func (_c *DKIMKeyCreate) SetDomain(v string) *DKIMKeyCreate {
	_c.mutation.SetDomain(v)
	return _c
}

// SetSelector sets the "selector" field.
func (_c *DKIMKeyCreate) SetSelector(v string) *DKIMKeyCreate {
	_c.mutation.SetSelector(v)
	return _c
}

// SetNillableSelector sets the "selector" field if the given value is not nil.
func (_c *DKIMKeyCreate) SetNillableSelector(v *string) *DKIMKeyCreate {
	if v != nil {
		_c.SetSelector(*v)
	}
	return _c
}

// SetPrivateKeyPem sets the "private_key_pem" field.
func (_c *DKIMKeyCreate) SetPrivateKeyPem(v string) *DKIMKeyCreate {
	_c.mutation.SetPrivateKeyPem(v)
	return _c
}

// SetPublicKeyPem sets the "public_key_pem" field.
func (_c *DKIMKeyCreate) SetPublicKeyPem(v string) *DKIMKeyCreate {
	_c.mutation.SetPublicKeyPem(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DKIMKeyCreate) SetCreatedAt(v time.Time) *DKIMKeyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DKIMKeyCreate) SetNillableCreatedAt(v *time.Time) *DKIMKeyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DKIMKeyCreate) SetUpdatedAt(v time.Time) *DKIMKeyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DKIMKeyCreate) SetNillableUpdatedAt(v *time.Time) *DKIMKeyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DKIMKeyCreate) SetID(v string) *DKIMKeyCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DKIMKeyCreate) SetNillableID(v *string) *DKIMKeyCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the DKIMKeyMutation object of the builder.
func (_c *DKIMKeyCreate) Mutation() *DKIMKeyMutation {
	return _c.mutation
}

// Save creates the DKIMKey in the database.
func (_c *DKIMKeyCreate) Save(ctx context.Context) (*DKIMKey, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DKIMKeyCreate) SaveX(ctx context.Context) *DKIMKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DKIMKeyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DKIMKeyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DKIMKeyCreate) defaults() {
	if _, ok := _c.mutation.Selector(); !ok {
		v := dkimkey.DefaultSelector
		_c.mutation.SetSelector(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := dkimkey.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := dkimkey.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := dkimkey.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DKIMKeyCreate) check() error {
	if _, ok := _c.mutation.Domain(); !ok {
		return &ValidationError{Name: "domain", err: errors.New(`ent: missing required field "DKIMKey.domain"`)}
	}
	if _, ok := _c.mutation.Selector(); !ok {
		return &ValidationError{Name: "selector", err: errors.New(`ent: missing required field "DKIMKey.selector"`)}
	}
	if _, ok := _c.mutation.PrivateKeyPem(); !ok {
		return &ValidationError{Name: "private_key_pem", err: errors.New(`ent: missing required field "DKIMKey.private_key_pem"`)}
	}
	if _, ok := _c.mutation.PublicKeyPem(); !ok {
		return &ValidationError{Name: "public_key_pem", err: errors.New(`ent: missing required field "DKIMKey.public_key_pem"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DKIMKey.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DKIMKey.updated_at"`)}
	}
	return nil
}

func (_c *DKIMKeyCreate) sqlSave(ctx context.Context) (*DKIMKey, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected DKIMKey.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DKIMKeyCreate) createSpec() (*DKIMKey, *sqlgraph.CreateSpec) {
	var (
		_node = &DKIMKey{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(dkimkey.Table, sqlgraph.NewFieldSpec(dkimkey.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Domain(); ok {
		_spec.SetField(dkimkey.FieldDomain, field.TypeString, value)
		_node.Domain = value
	}
	if value, ok := _c.mutation.Selector(); ok {
		_spec.SetField(dkimkey.FieldSelector, field.TypeString, value)
		_node.Selector = value
	}
	if value, ok := _c.mutation.PrivateKeyPem(); ok {
		_spec.SetField(dkimkey.FieldPrivateKeyPem, field.TypeString, value)
		_node.PrivateKeyPem = value
	}
	if value, ok := _c.mutation.PublicKeyPem(); ok {
		_spec.SetField(dkimkey.FieldPublicKeyPem, field.TypeString, value)
		_node.PublicKeyPem = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(dkimkey.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(dkimkey.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DKIMKey.Create().
//		SetDomain(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DKIMKeyUpsert) {
//			SetDomain(v+v).
//		}).
//		Exec(ctx)
func (_c *DKIMKeyCreate) OnConflict(opts ...sql.ConflictOption) *DKIMKeyUpsertOne {
	_c.conflict = opts
	return &DKIMKeyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DKIMKey.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DKIMKeyCreate) OnConflictColumns(columns ...string) *DKIMKeyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DKIMKeyUpsertOne{
		create: _c,
	}
}

type (
	// DKIMKeyUpsertOne is the builder for "upsert"-ing
	//  one DKIMKey node.
	DKIMKeyUpsertOne struct {
		create *DKIMKeyCreate
	}

	// DKIMKeyUpsert is the "OnConflict" setter.
	DKIMKeyUpsert struct {
		*sql.UpdateSet
	}
)

// SetDomain sets the "domain" field.
func (u *DKIMKeyUpsert) SetDomain(v string) *DKIMKeyUpsert {
	u.Set(dkimkey.FieldDomain, v)
	return u
}

// UpdateDomain sets the "domain" field to the value that was provided on create.
func (u *DKIMKeyUpsert) UpdateDomain() *DKIMKeyUpsert {
	u.SetExcluded(dkimkey.FieldDomain)
	return u
}

// SetSelector sets the "selector" field.
func (u *DKIMKeyUpsert) SetSelector(v string) *DKIMKeyUpsert {
	u.Set(dkimkey.FieldSelector, v)
	return u
}

// UpdateSelector sets the "selector" field to the value that was provided on create.
func (u *DKIMKeyUpsert) UpdateSelector() *DKIMKeyUpsert {
	u.SetExcluded(dkimkey.FieldSelector)
	return u
}

// SetPrivateKeyPem sets the "private_key_pem" field.
func (u *DKIMKeyUpsert) SetPrivateKeyPem(v string) *DKIMKeyUpsert {
	u.Set(dkimkey.FieldPrivateKeyPem, v)
	return u
}

// UpdatePrivateKeyPem sets the "private_key_pem" field to the value that was provided on create.
func (u *DKIMKeyUpsert) UpdatePrivateKeyPem() *DKIMKeyUpsert {
	u.SetExcluded(dkimkey.FieldPrivateKeyPem)
	return u
}

// SetPublicKeyPem sets the "public_key_pem" field.
func (u *DKIMKeyUpsert) SetPublicKeyPem(v string) *DKIMKeyUpsert {
	u.Set(dkimkey.FieldPublicKeyPem, v)
	return u
}

// UpdatePublicKeyPem sets the "public_key_pem" field to the value that was provided on create.
func (u *DKIMKeyUpsert) UpdatePublicKeyPem() *DKIMKeyUpsert {
	u.SetExcluded(dkimkey.FieldPublicKeyPem)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DKIMKeyUpsert) SetUpdatedAt(v time.Time) *DKIMKeyUpsert {
	u.Set(dkimkey.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DKIMKeyUpsert) UpdateUpdatedAt() *DKIMKeyUpsert {
	u.SetExcluded(dkimkey.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.DKIMKey.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(dkimkey.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DKIMKeyUpsertOne) UpdateNewValues() *DKIMKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(dkimkey.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(dkimkey.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DKIMKey.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DKIMKeyUpsertOne) Ignore() *DKIMKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DKIMKeyUpsertOne) DoNothing() *DKIMKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DKIMKeyCreate.OnConflict
// documentation for more info.
func (u *DKIMKeyUpsertOne) Update(set func(*DKIMKeyUpsert)) *DKIMKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DKIMKeyUpsert{UpdateSet: update})
	}))
	return u
}

// SetDomain sets the "domain" field.
func (u *DKIMKeyUpsertOne) SetDomain(v string) *DKIMKeyUpsertOne {
	return u.Update(func(s *DKIMKeyUpsert) {
		s.SetDomain(v)
	})
}

// UpdateDomain sets the "domain" field to the value that was provided on create.
func (u *DKIMKeyUpsertOne) UpdateDomain() *DKIMKeyUpsertOne {
	return u.Update(func(s *DKIMKeyUpsert) {
		s.UpdateDomain()
	})
}

// SetSelector sets the "selector" field.
func (u *DKIMKeyUpsertOne) SetSelector(v string) *DKIMKeyUpsertOne {
	return u.Update(func(s *DKIMKeyUpsert) {
		s.SetSelector(v)
	})
}

// UpdateSelector sets the "selector" field to the value that was provided on create.
func (u *DKIMKeyUpsertOne) UpdateSelector() *DKIMKeyUpsertOne {
	return u.Update(func(s *DKIMKeyUpsert) {
		s.UpdateSelector()
	})
}

// SetPrivateKeyPem sets the "private_key_pem" field.
func (u *DKIMKeyUpsertOne) SetPrivateKeyPem(v string) *DKIMKeyUpsertOne {
	return u.Update(func(s *DKIMKeyUpsert) {
		s.SetPrivateKeyPem(v)
	})
}

// UpdatePrivateKeyPem sets the "private_key_pem" field to the value that was provided on create.
func (u *DKIMKeyUpsertOne) UpdatePrivateKeyPem() *DKIMKeyUpsertOne {
	return u.Update(func(s *DKIMKeyUpsert) {
		s.UpdatePrivateKeyPem()
	})
}

// SetPublicKeyPem sets the "public_key_pem" field.
func (u *DKIMKeyUpsertOne) SetPublicKeyPem(v string) *DKIMKeyUpsertOne {
	return u.Update(func(s *DKIMKeyUpsert) {
		s.SetPublicKeyPem(v)
	})
}

// UpdatePublicKeyPem sets the "public_key_pem" field to the value that was provided on create.
func (u *DKIMKeyUpsertOne) UpdatePublicKeyPem() *DKIMKeyUpsertOne {
	return u.Update(func(s *DKIMKeyUpsert) {
		s.UpdatePublicKeyPem()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DKIMKeyUpsertOne) SetUpdatedAt(v time.Time) *DKIMKeyUpsertOne {
	return u.Update(func(s *DKIMKeyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DKIMKeyUpsertOne) UpdateUpdatedAt() *DKIMKeyUpsertOne {
	return u.Update(func(s *DKIMKeyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *DKIMKeyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DKIMKeyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DKIMKeyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DKIMKeyUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: DKIMKeyUpsertOne.ID is not supported by MySQL driver. Use DKIMKeyUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DKIMKeyUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DKIMKeyCreateBulk is the builder for creating many DKIMKey entities in bulk.
type DKIMKeyCreateBulk struct {
	config
	err      error
	builders []*DKIMKeyCreate
	conflict []sql.ConflictOption
}

// Save creates the DKIMKey entities in the database.
func (_c *DKIMKeyCreateBulk) Save(ctx context.Context) ([]*DKIMKey, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DKIMKey, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DKIMKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DKIMKeyCreateBulk) SaveX(ctx context.Context) []*DKIMKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DKIMKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DKIMKeyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DKIMKey.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DKIMKeyUpsert) {
//			SetDomain(v+v).
//		}).
//		Exec(ctx)
func (_c *DKIMKeyCreateBulk) OnConflict(opts ...sql.ConflictOption) *DKIMKeyUpsertBulk {
	_c.conflict = opts
	return &DKIMKeyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DKIMKey.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DKIMKeyCreateBulk) OnConflictColumns(columns ...string) *DKIMKeyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DKIMKeyUpsertBulk{
		create: _c,
	}
}

// DKIMKeyUpsertBulk is the builder for "upsert"-ing
// a bulk of DKIMKey nodes.
type DKIMKeyUpsertBulk struct {
	create *DKIMKeyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DKIMKey.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(dkimkey.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DKIMKeyUpsertBulk) UpdateNewValues() *DKIMKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(dkimkey.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(dkimkey.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DKIMKey.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DKIMKeyUpsertBulk) Ignore() *DKIMKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DKIMKeyUpsertBulk) DoNothing() *DKIMKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DKIMKeyCreateBulk.OnConflict
// documentation for more info.
func (u *DKIMKeyUpsertBulk) Update(set func(*DKIMKeyUpsert)) *DKIMKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DKIMKeyUpsert{UpdateSet: update})
	}))
	return u
}

// SetDomain sets the "domain" field.
func (u *DKIMKeyUpsertBulk) SetDomain(v string) *DKIMKeyUpsertBulk {
	return u.Update(func(s *DKIMKeyUpsert) {
		s.SetDomain(v)
	})
}

// UpdateDomain sets the "domain" field to the value that was provided on create.
func (u *DKIMKeyUpsertBulk) UpdateDomain() *DKIMKeyUpsertBulk {
	return u.Update(func(s *DKIMKeyUpsert) {
		s.UpdateDomain()
	})
}

// SetSelector sets the "selector" field.
func (u *DKIMKeyUpsertBulk) SetSelector(v string) *DKIMKeyUpsertBulk {
	return u.Update(func(s *DKIMKeyUpsert) {
		s.SetSelector(v)
	})
}

// UpdateSelector sets the "selector" field to the value that was provided on create.
func (u *DKIMKeyUpsertBulk) UpdateSelector() *DKIMKeyUpsertBulk {
	return u.Update(func(s *DKIMKeyUpsert) {
		s.UpdateSelector()
	})
}

// SetPrivateKeyPem sets the "private_key_pem" field.
func (u *DKIMKeyUpsertBulk) SetPrivateKeyPem(v string) *DKIMKeyUpsertBulk {
	return u.Update(func(s *DKIMKeyUpsert) {
		s.SetPrivateKeyPem(v)
	})
}

// UpdatePrivateKeyPem sets the "private_key_pem" field to the value that was provided on create.
func (u *DKIMKeyUpsertBulk) UpdatePrivateKeyPem() *DKIMKeyUpsertBulk {
	return u.Update(func(s *DKIMKeyUpsert) {
		s.UpdatePrivateKeyPem()
	})
}

// SetPublicKeyPem sets the "public_key_pem" field.
func (u *DKIMKeyUpsertBulk) SetPublicKeyPem(v string) *DKIMKeyUpsertBulk {
	return u.Update(func(s *DKIMKeyUpsert) {
		s.SetPublicKeyPem(v)
	})
}

// UpdatePublicKeyPem sets the "public_key_pem" field to the value that was provided on create.
func (u *DKIMKeyUpsertBulk) UpdatePublicKeyPem() *DKIMKeyUpsertBulk {
	return u.Update(func(s *DKIMKeyUpsert) {
		s.UpdatePublicKeyPem()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DKIMKeyUpsertBulk) SetUpdatedAt(v time.Time) *DKIMKeyUpsertBulk {
	return u.Update(func(s *DKIMKeyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DKIMKeyUpsertBulk) UpdateUpdatedAt() *DKIMKeyUpsertBulk {
	return u.Update(func(s *DKIMKeyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *DKIMKeyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DKIMKeyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DKIMKeyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DKIMKeyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
