// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zephyraoss/haitatsu/internal/database/ent/eventlog"
)

// EventLogCreate is the builder for creating a EventLog entity.
type EventLogCreate struct {
	config
	mutation *EventLogMutation
	hooks    []Hook
}

// SetEventType sets the "event_type" field.
func (_c *EventLogCreate) SetEventType(v string) *EventLogCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetTraceID sets the "trace_id" field.
func (_c *EventLogCreate) SetTraceID(v string) *EventLogCreate {
	_c.mutation.SetTraceID(v)
	return _c
}

// SetNillableTraceID sets the "trace_id" field if the given value is not nil.
func (_c *EventLogCreate) SetNillableTraceID(v *string) *EventLogCreate {
	if v != nil {
		_c.SetTraceID(*v)
	}
	return _c
}

// SetMessageID sets the "message_id" field.
func (_c *EventLogCreate) SetMessageID(v string) *EventLogCreate {
	_c.mutation.SetMessageID(v)
	return _c
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_c *EventLogCreate) SetNillableMessageID(v *string) *EventLogCreate {
	if v != nil {
		_c.SetMessageID(*v)
	}
	return _c
}

// SetMailboxID sets the "mailbox_id" field.
func (_c *EventLogCreate) SetMailboxID(v string) *EventLogCreate {
	_c.mutation.SetMailboxID(v)
	return _c
}

// SetNillableMailboxID sets the "mailbox_id" field if the given value is not nil.
func (_c *EventLogCreate) SetNillableMailboxID(v *string) *EventLogCreate {
	if v != nil {
		_c.SetMailboxID(*v)
	}
	return _c
}

// SetPayload sets the "payload" field.
func (_c *EventLogCreate) SetPayload(v map[string]interface{}) *EventLogCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *EventLogCreate) SetStatus(v string) *EventLogCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *EventLogCreate) SetNillableStatus(v *string) *EventLogCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAttempts sets the "attempts" field.
func (_c *EventLogCreate) SetAttempts(v int) *EventLogCreate {
	_c.mutation.SetAttempts(v)
	return _c
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_c *EventLogCreate) SetNillableAttempts(v *int) *EventLogCreate {
	if v != nil {
		_c.SetAttempts(*v)
	}
	return _c
}

// SetLockedBy sets the "locked_by" field.
func (_c *EventLogCreate) SetLockedBy(v string) *EventLogCreate {
	_c.mutation.SetLockedBy(v)
	return _c
}

// SetNillableLockedBy sets the "locked_by" field if the given value is not nil.
func (_c *EventLogCreate) SetNillableLockedBy(v *string) *EventLogCreate {
	if v != nil {
		_c.SetLockedBy(*v)
	}
	return _c
}

// SetLockedUntil sets the "locked_until" field.
func (_c *EventLogCreate) SetLockedUntil(v time.Time) *EventLogCreate {
	_c.mutation.SetLockedUntil(v)
	return _c
}

// SetNillableLockedUntil sets the "locked_until" field if the given value is not nil.
func (_c *EventLogCreate) SetNillableLockedUntil(v *time.Time) *EventLogCreate {
	if v != nil {
		_c.SetLockedUntil(*v)
	}
	return _c
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_c *EventLogCreate) SetNextAttemptAt(v time.Time) *EventLogCreate {
	_c.mutation.SetNextAttemptAt(v)
	return _c
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_c *EventLogCreate) SetNillableNextAttemptAt(v *time.Time) *EventLogCreate {
	if v != nil {
		_c.SetNextAttemptAt(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *EventLogCreate) SetLastError(v map[string]interface{}) *EventLogCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EventLogCreate) SetCreatedAt(v time.Time) *EventLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EventLogCreate) SetNillableCreatedAt(v *time.Time) *EventLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EventLogCreate) SetUpdatedAt(v time.Time) *EventLogCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EventLogCreate) SetNillableUpdatedAt(v *time.Time) *EventLogCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *EventLogCreate) SetID(v string) *EventLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *EventLogCreate) SetNillableID(v *string) *EventLogCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the EventLogMutation object of the builder.
func (_c *EventLogCreate) Mutation() *EventLogMutation {
	return _c.mutation
}

// Save creates the EventLog in the database.
func (_c *EventLogCreate) Save(ctx context.Context) (*EventLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EventLogCreate) SaveX(ctx context.Context) *EventLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EventLogCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := eventlog.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		v := eventlog.DefaultAttempts
		_c.mutation.SetAttempts(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := eventlog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := eventlog.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := eventlog.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EventLogCreate) check() error {
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "EventLog.event_type"`)}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "EventLog.payload"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "EventLog.status"`)}
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "EventLog.attempts"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EventLog.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EventLog.updated_at"`)}
	}
	return nil
}

func (_c *EventLogCreate) sqlSave(ctx context.Context) (*EventLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected EventLog.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EventLogCreate) createSpec() (*EventLog, *sqlgraph.CreateSpec) {
	var (
		_node = &EventLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(eventlog.Table, sqlgraph.NewFieldSpec(eventlog.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(eventlog.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.TraceID(); ok {
		_spec.SetField(eventlog.FieldTraceID, field.TypeString, value)
		_node.TraceID = value
	}
	if value, ok := _c.mutation.MessageID(); ok {
		_spec.SetField(eventlog.FieldMessageID, field.TypeString, value)
		_node.MessageID = value
	}
	if value, ok := _c.mutation.MailboxID(); ok {
		_spec.SetField(eventlog.FieldMailboxID, field.TypeString, value)
		_node.MailboxID = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(eventlog.FieldPayload, field.TypeJSON, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(eventlog.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Attempts(); ok {
		_spec.SetField(eventlog.FieldAttempts, field.TypeInt, value)
		_node.Attempts = value
	}
	if value, ok := _c.mutation.LockedBy(); ok {
		_spec.SetField(eventlog.FieldLockedBy, field.TypeString, value)
		_node.LockedBy = value
	}
	if value, ok := _c.mutation.LockedUntil(); ok {
		_spec.SetField(eventlog.FieldLockedUntil, field.TypeTime, value)
		_node.LockedUntil = &value
	}
	if value, ok := _c.mutation.NextAttemptAt(); ok {
		_spec.SetField(eventlog.FieldNextAttemptAt, field.TypeTime, value)
		_node.NextAttemptAt = &value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(eventlog.FieldLastError, field.TypeJSON, value)
		_node.LastError = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(eventlog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(eventlog.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// EventLogCreateBulk is the builder for creating many EventLog entities in bulk.
type EventLogCreateBulk struct {
	config
	err      error
	builders []*EventLogCreate
}

// Save creates the EventLog entities in the database.
func (_c *EventLogCreateBulk) Save(ctx context.Context) ([]*EventLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EventLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EventLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EventLogCreateBulk) SaveX(ctx context.Context) []*EventLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
