// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/zephyraoss/haitatsu/internal/database/ent/eventlog"
)

// EventLog is the model entity for the EventLog schema.
type EventLog struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// EventType holds the value of the "event_type" field.
	EventType string `json:"event_type,omitempty"`
	// TraceID holds the value of the "trace_id" field.
	TraceID string `json:"trace_id,omitempty"`
	// MessageID holds the value of the "message_id" field.
	MessageID string `json:"message_id,omitempty"`
	// MailboxID holds the value of the "mailbox_id" field.
	MailboxID string `json:"mailbox_id,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload map[string]interface{} `json:"payload,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Attempts holds the value of the "attempts" field.
	Attempts int `json:"attempts,omitempty"`
	// LockedBy holds the value of the "locked_by" field.
	LockedBy string `json:"locked_by,omitempty"`
	// LockedUntil holds the value of the "locked_until" field.
	LockedUntil *time.Time `json:"locked_until,omitempty"`
	// NextAttemptAt holds the value of the "next_attempt_at" field.
	NextAttemptAt *time.Time `json:"next_attempt_at,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError map[string]interface{} `json:"last_error,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EventLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case eventlog.FieldPayload, eventlog.FieldLastError:
			values[i] = new([]byte)
		case eventlog.FieldAttempts:
			values[i] = new(sql.NullInt64)
		case eventlog.FieldID, eventlog.FieldEventType, eventlog.FieldTraceID, eventlog.FieldMessageID, eventlog.FieldMailboxID, eventlog.FieldStatus, eventlog.FieldLockedBy:
			values[i] = new(sql.NullString)
		case eventlog.FieldLockedUntil, eventlog.FieldNextAttemptAt, eventlog.FieldCreatedAt, eventlog.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EventLog fields.
func (_m *EventLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case eventlog.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case eventlog.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				_m.EventType = value.String
			}
		case eventlog.FieldTraceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trace_id", values[i])
			} else if value.Valid {
				_m.TraceID = value.String
			}
		case eventlog.FieldMessageID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message_id", values[i])
			} else if value.Valid {
				_m.MessageID = value.String
			}
		case eventlog.FieldMailboxID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mailbox_id", values[i])
			} else if value.Valid {
				_m.MailboxID = value.String
			}
		case eventlog.FieldPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Payload); err != nil {
					return fmt.Errorf("unmarshal field payload: %w", err)
				}
			}
		case eventlog.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case eventlog.FieldAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempts", values[i])
			} else if value.Valid {
				_m.Attempts = int(value.Int64)
			}
		case eventlog.FieldLockedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field locked_by", values[i])
			} else if value.Valid {
				_m.LockedBy = value.String
			}
		case eventlog.FieldLockedUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field locked_until", values[i])
			} else if value.Valid {
				_m.LockedUntil = new(time.Time)
				*_m.LockedUntil = value.Time
			}
		case eventlog.FieldNextAttemptAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_attempt_at", values[i])
			} else if value.Valid {
				_m.NextAttemptAt = new(time.Time)
				*_m.NextAttemptAt = value.Time
			}
		case eventlog.FieldLastError:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.LastError); err != nil {
					return fmt.Errorf("unmarshal field last_error: %w", err)
				}
			}
		case eventlog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case eventlog.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EventLog.
// This includes values selected through modifiers, order, etc.
func (_m *EventLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this EventLog.
// Note that you need to call EventLog.Unwrap() before calling this method if this EventLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EventLog) Update() *EventLogUpdateOne {
	return NewEventLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EventLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EventLog) Unwrap() *EventLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EventLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EventLog) String() string {
	var builder strings.Builder
	builder.WriteString("EventLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("event_type=")
	builder.WriteString(_m.EventType)
	builder.WriteString(", ")
	builder.WriteString("trace_id=")
	builder.WriteString(_m.TraceID)
	builder.WriteString(", ")
	builder.WriteString("message_id=")
	builder.WriteString(_m.MessageID)
	builder.WriteString(", ")
	builder.WriteString("mailbox_id=")
	builder.WriteString(_m.MailboxID)
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.Payload))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("attempts=")
	builder.WriteString(fmt.Sprintf("%v", _m.Attempts))
	builder.WriteString(", ")
	builder.WriteString("locked_by=")
	builder.WriteString(_m.LockedBy)
	builder.WriteString(", ")
	if v := _m.LockedUntil; v != nil {
		builder.WriteString("locked_until=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.NextAttemptAt; v != nil {
		builder.WriteString("next_attempt_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("last_error=")
	builder.WriteString(fmt.Sprintf("%v", _m.LastError))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// EventLogs is a parsable slice of EventLog.
type EventLogs []*EventLog
