// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zephyraoss/haitatsu/internal/database/ent/exportjob"
)

// ExportJobCreate is the builder for creating a ExportJob entity.
type ExportJobCreate struct {
	config
	mutation *ExportJobMutation
	hooks    []Hook
}

// SetMailboxID sets the "mailbox_id" field.
func (_c *ExportJobCreate) SetMailboxID(v string) *ExportJobCreate {
	_c.mutation.SetMailboxID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ExportJobCreate) SetStatus(v string) *ExportJobCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ExportJobCreate) SetNillableStatus(v *string) *ExportJobCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetObjectKey sets the "object_key" field.
func (_c *ExportJobCreate) SetObjectKey(v string) *ExportJobCreate {
	_c.mutation.SetObjectKey(v)
	return _c
}

// SetNillableObjectKey sets the "object_key" field if the given value is not nil.
func (_c *ExportJobCreate) SetNillableObjectKey(v *string) *ExportJobCreate {
	if v != nil {
		_c.SetObjectKey(*v)
	}
	return _c
}

// SetSizeBytes sets the "size_bytes" field.
func (_c *ExportJobCreate) SetSizeBytes(v int64) *ExportJobCreate {
	_c.mutation.SetSizeBytes(v)
	return _c
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_c *ExportJobCreate) SetNillableSizeBytes(v *int64) *ExportJobCreate {
	if v != nil {
		_c.SetSizeBytes(*v)
	}
	return _c
}

// SetLockedBy sets the "locked_by" field.
func (_c *ExportJobCreate) SetLockedBy(v string) *ExportJobCreate {
	_c.mutation.SetLockedBy(v)
	return _c
}

// SetNillableLockedBy sets the "locked_by" field if the given value is not nil.
func (_c *ExportJobCreate) SetNillableLockedBy(v *string) *ExportJobCreate {
	if v != nil {
		_c.SetLockedBy(*v)
	}
	return _c
}

// SetLockedUntil sets the "locked_until" field.
func (_c *ExportJobCreate) SetLockedUntil(v time.Time) *ExportJobCreate {
	_c.mutation.SetLockedUntil(v)
	return _c
}

// SetNillableLockedUntil sets the "locked_until" field if the given value is not nil.
func (_c *ExportJobCreate) SetNillableLockedUntil(v *time.Time) *ExportJobCreate {
	if v != nil {
		_c.SetLockedUntil(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *ExportJobCreate) SetLastError(v map[string]interface{}) *ExportJobCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *ExportJobCreate) SetExpiresAt(v time.Time) *ExportJobCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *ExportJobCreate) SetNillableExpiresAt(v *time.Time) *ExportJobCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ExportJobCreate) SetCreatedAt(v time.Time) *ExportJobCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ExportJobCreate) SetNillableCreatedAt(v *time.Time) *ExportJobCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ExportJobCreate) SetUpdatedAt(v time.Time) *ExportJobCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ExportJobCreate) SetNillableUpdatedAt(v *time.Time) *ExportJobCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ExportJobCreate) SetID(v string) *ExportJobCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ExportJobCreate) SetNillableID(v *string) *ExportJobCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ExportJobMutation object of the builder.
func (_c *ExportJobCreate) Mutation() *ExportJobMutation {
	return _c.mutation
}

// Save creates the ExportJob in the database.
func (_c *ExportJobCreate) Save(ctx context.Context) (*ExportJob, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExportJobCreate) SaveX(ctx context.Context) *ExportJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExportJobCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExportJobCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ExportJobCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := exportjob.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.SizeBytes(); !ok {
		v := exportjob.DefaultSizeBytes
		_c.mutation.SetSizeBytes(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := exportjob.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := exportjob.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := exportjob.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExportJobCreate) check() error {
	if _, ok := _c.mutation.MailboxID(); !ok {
		return &ValidationError{Name: "mailbox_id", err: errors.New(`ent: missing required field "ExportJob.mailbox_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ExportJob.status"`)}
	}
	if _, ok := _c.mutation.SizeBytes(); !ok {
		return &ValidationError{Name: "size_bytes", err: errors.New(`ent: missing required field "ExportJob.size_bytes"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ExportJob.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ExportJob.updated_at"`)}
	}
	return nil
}

func (_c *ExportJobCreate) sqlSave(ctx context.Context) (*ExportJob, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ExportJob.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExportJobCreate) createSpec() (*ExportJob, *sqlgraph.CreateSpec) {
	var (
		_node = &ExportJob{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(exportjob.Table, sqlgraph.NewFieldSpec(exportjob.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.MailboxID(); ok {
		_spec.SetField(exportjob.FieldMailboxID, field.TypeString, value)
		_node.MailboxID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(exportjob.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ObjectKey(); ok {
		_spec.SetField(exportjob.FieldObjectKey, field.TypeString, value)
		_node.ObjectKey = value
	}
	if value, ok := _c.mutation.SizeBytes(); ok {
		_spec.SetField(exportjob.FieldSizeBytes, field.TypeInt64, value)
		_node.SizeBytes = value
	}
	if value, ok := _c.mutation.LockedBy(); ok {
		_spec.SetField(exportjob.FieldLockedBy, field.TypeString, value)
		_node.LockedBy = value
	}
	if value, ok := _c.mutation.LockedUntil(); ok {
		_spec.SetField(exportjob.FieldLockedUntil, field.TypeTime, value)
		_node.LockedUntil = &value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(exportjob.FieldLastError, field.TypeJSON, value)
		_node.LastError = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(exportjob.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(exportjob.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(exportjob.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ExportJobCreateBulk is the builder for creating many ExportJob entities in bulk.
type ExportJobCreateBulk struct {
	config
	err      error
	builders []*ExportJobCreate
}

// Save creates the ExportJob entities in the database.
func (_c *ExportJobCreateBulk) Save(ctx context.Context) ([]*ExportJob, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ExportJob, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExportJobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExportJobCreateBulk) SaveX(ctx context.Context) []*ExportJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExportJobCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExportJobCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
