// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zephyraoss/haitatsu/internal/database/ent/mailbox"
	"github.com/zephyraoss/haitatsu/internal/database/ent/predicate"
)

// MailboxUpdate is the builder for updating Mailbox entities.
type MailboxUpdate struct {
	config
	hooks    []Hook
	mutation *MailboxMutation
}

// Where appends a list predicates to the MailboxUpdate builder.
func (_u *MailboxUpdate) Where(ps ...predicate.Mailbox) *MailboxUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPrimaryAddress sets the "primary_address" field.
func (_u *MailboxUpdate) SetPrimaryAddress(v string) *MailboxUpdate {
	_u.mutation.SetPrimaryAddress(v)
	return _u
}

// SetNillablePrimaryAddress sets the "primary_address" field if the given value is not nil.
func (_u *MailboxUpdate) SetNillablePrimaryAddress(v *string) *MailboxUpdate {
	if v != nil {
		_u.SetPrimaryAddress(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *MailboxUpdate) SetStatus(v string) *MailboxUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MailboxUpdate) SetNillableStatus(v *string) *MailboxUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetQuotaBytes sets the "quota_bytes" field.
func (_u *MailboxUpdate) SetQuotaBytes(v int64) *MailboxUpdate {
	_u.mutation.ResetQuotaBytes()
	_u.mutation.SetQuotaBytes(v)
	return _u
}

// SetNillableQuotaBytes sets the "quota_bytes" field if the given value is not nil.
func (_u *MailboxUpdate) SetNillableQuotaBytes(v *int64) *MailboxUpdate {
	if v != nil {
		_u.SetQuotaBytes(*v)
	}
	return _u
}

// AddQuotaBytes adds value to the "quota_bytes" field.
func (_u *MailboxUpdate) AddQuotaBytes(v int64) *MailboxUpdate {
	_u.mutation.AddQuotaBytes(v)
	return _u
}

// SetUsedBytes sets the "used_bytes" field.
func (_u *MailboxUpdate) SetUsedBytes(v int64) *MailboxUpdate {
	_u.mutation.ResetUsedBytes()
	_u.mutation.SetUsedBytes(v)
	return _u
}

// SetNillableUsedBytes sets the "used_bytes" field if the given value is not nil.
func (_u *MailboxUpdate) SetNillableUsedBytes(v *int64) *MailboxUpdate {
	if v != nil {
		_u.SetUsedBytes(*v)
	}
	return _u
}

// AddUsedBytes adds value to the "used_bytes" field.
func (_u *MailboxUpdate) AddUsedBytes(v int64) *MailboxUpdate {
	_u.mutation.AddUsedBytes(v)
	return _u
}

// SetOutboundLimits sets the "outbound_limits" field.
func (_u *MailboxUpdate) SetOutboundLimits(v map[string]int64) *MailboxUpdate {
	_u.mutation.SetOutboundLimits(v)
	return _u
}

// ClearOutboundLimits clears the value of the "outbound_limits" field.
func (_u *MailboxUpdate) ClearOutboundLimits() *MailboxUpdate {
	_u.mutation.ClearOutboundLimits()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MailboxUpdate) SetUpdatedAt(v time.Time) *MailboxUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *MailboxUpdate) SetDeletedAt(v time.Time) *MailboxUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *MailboxUpdate) SetNillableDeletedAt(v *time.Time) *MailboxUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *MailboxUpdate) ClearDeletedAt() *MailboxUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// Mutation returns the MailboxMutation object of the builder.
func (_u *MailboxUpdate) Mutation() *MailboxMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MailboxUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MailboxUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MailboxUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MailboxUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MailboxUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := mailbox.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *MailboxUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(mailbox.Table, mailbox.Columns, sqlgraph.NewFieldSpec(mailbox.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PrimaryAddress(); ok {
		_spec.SetField(mailbox.FieldPrimaryAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(mailbox.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.QuotaBytes(); ok {
		_spec.SetField(mailbox.FieldQuotaBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedQuotaBytes(); ok {
		_spec.AddField(mailbox.FieldQuotaBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UsedBytes(); ok {
		_spec.SetField(mailbox.FieldUsedBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsedBytes(); ok {
		_spec.AddField(mailbox.FieldUsedBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutboundLimits(); ok {
		_spec.SetField(mailbox.FieldOutboundLimits, field.TypeJSON, value)
	}
	if _u.mutation.OutboundLimitsCleared() {
		_spec.ClearField(mailbox.FieldOutboundLimits, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mailbox.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(mailbox.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(mailbox.FieldDeletedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mailbox.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MailboxUpdateOne is the builder for updating a single Mailbox entity.
type MailboxUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MailboxMutation
}

// SetPrimaryAddress sets the "primary_address" field.
func (_u *MailboxUpdateOne) SetPrimaryAddress(v string) *MailboxUpdateOne {
	_u.mutation.SetPrimaryAddress(v)
	return _u
}

// SetNillablePrimaryAddress sets the "primary_address" field if the given value is not nil.
func (_u *MailboxUpdateOne) SetNillablePrimaryAddress(v *string) *MailboxUpdateOne {
	if v != nil {
		_u.SetPrimaryAddress(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *MailboxUpdateOne) SetStatus(v string) *MailboxUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MailboxUpdateOne) SetNillableStatus(v *string) *MailboxUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetQuotaBytes sets the "quota_bytes" field.
func (_u *MailboxUpdateOne) SetQuotaBytes(v int64) *MailboxUpdateOne {
	_u.mutation.ResetQuotaBytes()
	_u.mutation.SetQuotaBytes(v)
	return _u
}

// SetNillableQuotaBytes sets the "quota_bytes" field if the given value is not nil.
func (_u *MailboxUpdateOne) SetNillableQuotaBytes(v *int64) *MailboxUpdateOne {
	if v != nil {
		_u.SetQuotaBytes(*v)
	}
	return _u
}

// AddQuotaBytes adds value to the "quota_bytes" field.
func (_u *MailboxUpdateOne) AddQuotaBytes(v int64) *MailboxUpdateOne {
	_u.mutation.AddQuotaBytes(v)
	return _u
}

// SetUsedBytes sets the "used_bytes" field.
func (_u *MailboxUpdateOne) SetUsedBytes(v int64) *MailboxUpdateOne {
	_u.mutation.ResetUsedBytes()
	_u.mutation.SetUsedBytes(v)
	return _u
}

// SetNillableUsedBytes sets the "used_bytes" field if the given value is not nil.
func (_u *MailboxUpdateOne) SetNillableUsedBytes(v *int64) *MailboxUpdateOne {
	if v != nil {
		_u.SetUsedBytes(*v)
	}
	return _u
}

// AddUsedBytes adds value to the "used_bytes" field.
func (_u *MailboxUpdateOne) AddUsedBytes(v int64) *MailboxUpdateOne {
	_u.mutation.AddUsedBytes(v)
	return _u
}

// SetOutboundLimits sets the "outbound_limits" field.
func (_u *MailboxUpdateOne) SetOutboundLimits(v map[string]int64) *MailboxUpdateOne {
	_u.mutation.SetOutboundLimits(v)
	return _u
}

// ClearOutboundLimits clears the value of the "outbound_limits" field.
func (_u *MailboxUpdateOne) ClearOutboundLimits() *MailboxUpdateOne {
	_u.mutation.ClearOutboundLimits()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MailboxUpdateOne) SetUpdatedAt(v time.Time) *MailboxUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *MailboxUpdateOne) SetDeletedAt(v time.Time) *MailboxUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *MailboxUpdateOne) SetNillableDeletedAt(v *time.Time) *MailboxUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *MailboxUpdateOne) ClearDeletedAt() *MailboxUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// Mutation returns the MailboxMutation object of the builder.
func (_u *MailboxUpdateOne) Mutation() *MailboxMutation {
	return _u.mutation
}

// Where appends a list predicates to the MailboxUpdate builder.
func (_u *MailboxUpdateOne) Where(ps ...predicate.Mailbox) *MailboxUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MailboxUpdateOne) Select(field string, fields ...string) *MailboxUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Mailbox entity.
func (_u *MailboxUpdateOne) Save(ctx context.Context) (*Mailbox, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MailboxUpdateOne) SaveX(ctx context.Context) *Mailbox {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MailboxUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MailboxUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MailboxUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := mailbox.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *MailboxUpdateOne) sqlSave(ctx context.Context) (_node *Mailbox, err error) {
	_spec := sqlgraph.NewUpdateSpec(mailbox.Table, mailbox.Columns, sqlgraph.NewFieldSpec(mailbox.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Mailbox.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mailbox.FieldID)
		for _, f := range fields {
			if !mailbox.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mailbox.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PrimaryAddress(); ok {
		_spec.SetField(mailbox.FieldPrimaryAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(mailbox.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.QuotaBytes(); ok {
		_spec.SetField(mailbox.FieldQuotaBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedQuotaBytes(); ok {
		_spec.AddField(mailbox.FieldQuotaBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UsedBytes(); ok {
		_spec.SetField(mailbox.FieldUsedBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsedBytes(); ok {
		_spec.AddField(mailbox.FieldUsedBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutboundLimits(); ok {
		_spec.SetField(mailbox.FieldOutboundLimits, field.TypeJSON, value)
	}
	if _u.mutation.OutboundLimitsCleared() {
		_spec.ClearField(mailbox.FieldOutboundLimits, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mailbox.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(mailbox.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(mailbox.FieldDeletedAt, field.TypeTime)
	}
	_node = &Mailbox{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mailbox.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
