// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zephyraoss/haitatsu/internal/database/ent/mailbox"
)

// MailboxCreate is the builder for creating a Mailbox entity.
type MailboxCreate struct {
	config
	mutation *MailboxMutation
	hooks    []Hook
}

// SetPrimaryAddress sets the "primary_address" field.
func (_c *MailboxCreate) SetPrimaryAddress(v string) *MailboxCreate {
	_c.mutation.SetPrimaryAddress(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *MailboxCreate) SetStatus(v string) *MailboxCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *MailboxCreate) SetNillableStatus(v *string) *MailboxCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetQuotaBytes sets the "quota_bytes" field.
func (_c *MailboxCreate) SetQuotaBytes(v int64) *MailboxCreate {
	_c.mutation.SetQuotaBytes(v)
	return _c
}

// SetNillableQuotaBytes sets the "quota_bytes" field if the given value is not nil.
func (_c *MailboxCreate) SetNillableQuotaBytes(v *int64) *MailboxCreate {
	if v != nil {
		_c.SetQuotaBytes(*v)
	}
	return _c
}

// SetUsedBytes sets the "used_bytes" field.
func (_c *MailboxCreate) SetUsedBytes(v int64) *MailboxCreate {
	_c.mutation.SetUsedBytes(v)
	return _c
}

// SetNillableUsedBytes sets the "used_bytes" field if the given value is not nil.
func (_c *MailboxCreate) SetNillableUsedBytes(v *int64) *MailboxCreate {
	if v != nil {
		_c.SetUsedBytes(*v)
	}
	return _c
}

// SetOutboundLimits sets the "outbound_limits" field.
func (_c *MailboxCreate) SetOutboundLimits(v map[string]int64) *MailboxCreate {
	_c.mutation.SetOutboundLimits(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MailboxCreate) SetCreatedAt(v time.Time) *MailboxCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MailboxCreate) SetNillableCreatedAt(v *time.Time) *MailboxCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MailboxCreate) SetUpdatedAt(v time.Time) *MailboxCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MailboxCreate) SetNillableUpdatedAt(v *time.Time) *MailboxCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *MailboxCreate) SetDeletedAt(v time.Time) *MailboxCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *MailboxCreate) SetNillableDeletedAt(v *time.Time) *MailboxCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MailboxCreate) SetID(v string) *MailboxCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *MailboxCreate) SetNillableID(v *string) *MailboxCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the MailboxMutation object of the builder.
func (_c *MailboxCreate) Mutation() *MailboxMutation {
	return _c.mutation
}

// Save creates the Mailbox in the database.
func (_c *MailboxCreate) Save(ctx context.Context) (*Mailbox, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MailboxCreate) SaveX(ctx context.Context) *Mailbox {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MailboxCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MailboxCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MailboxCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := mailbox.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.QuotaBytes(); !ok {
		v := mailbox.DefaultQuotaBytes
		_c.mutation.SetQuotaBytes(v)
	}
	if _, ok := _c.mutation.UsedBytes(); !ok {
		v := mailbox.DefaultUsedBytes
		_c.mutation.SetUsedBytes(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := mailbox.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := mailbox.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := mailbox.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MailboxCreate) check() error {
	if _, ok := _c.mutation.PrimaryAddress(); !ok {
		return &ValidationError{Name: "primary_address", err: errors.New(`ent: missing required field "Mailbox.primary_address"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Mailbox.status"`)}
	}
	if _, ok := _c.mutation.QuotaBytes(); !ok {
		return &ValidationError{Name: "quota_bytes", err: errors.New(`ent: missing required field "Mailbox.quota_bytes"`)}
	}
	if _, ok := _c.mutation.UsedBytes(); !ok {
		return &ValidationError{Name: "used_bytes", err: errors.New(`ent: missing required field "Mailbox.used_bytes"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Mailbox.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Mailbox.updated_at"`)}
	}
	return nil
}

func (_c *MailboxCreate) sqlSave(ctx context.Context) (*Mailbox, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Mailbox.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MailboxCreate) createSpec() (*Mailbox, *sqlgraph.CreateSpec) {
	var (
		_node = &Mailbox{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mailbox.Table, sqlgraph.NewFieldSpec(mailbox.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.PrimaryAddress(); ok {
		_spec.SetField(mailbox.FieldPrimaryAddress, field.TypeString, value)
		_node.PrimaryAddress = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(mailbox.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.QuotaBytes(); ok {
		_spec.SetField(mailbox.FieldQuotaBytes, field.TypeInt64, value)
		_node.QuotaBytes = value
	}
	if value, ok := _c.mutation.UsedBytes(); ok {
		_spec.SetField(mailbox.FieldUsedBytes, field.TypeInt64, value)
		_node.UsedBytes = value
	}
	if value, ok := _c.mutation.OutboundLimits(); ok {
		_spec.SetField(mailbox.FieldOutboundLimits, field.TypeJSON, value)
		_node.OutboundLimits = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(mailbox.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(mailbox.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(mailbox.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	return _node, _spec
}

// MailboxCreateBulk is the builder for creating many Mailbox entities in bulk.
type MailboxCreateBulk struct {
	config
	err      error
	builders []*MailboxCreate
}

// Save creates the Mailbox entities in the database.
func (_c *MailboxCreateBulk) Save(ctx context.Context) ([]*Mailbox, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Mailbox, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MailboxMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MailboxCreateBulk) SaveX(ctx context.Context) []*Mailbox {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MailboxCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MailboxCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
