// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zephyraoss/haitatsu/internal/database/ent/mailboxmessage"
)

// MailboxMessageCreate is the builder for creating a MailboxMessage entity.
type MailboxMessageCreate struct {
	config
	mutation *MailboxMessageMutation
	hooks    []Hook
}

// SetMailboxID sets the "mailbox_id" field.
func (_c *MailboxMessageCreate) SetMailboxID(v string) *MailboxMessageCreate {
	_c.mutation.SetMailboxID(v)
	return _c
}

// SetMessageID sets the "message_id" field.
func (_c *MailboxMessageCreate) SetMessageID(v string) *MailboxMessageCreate {
	_c.mutation.SetMessageID(v)
	return _c
}

// SetFolderID sets the "folder_id" field.
func (_c *MailboxMessageCreate) SetFolderID(v string) *MailboxMessageCreate {
	_c.mutation.SetFolderID(v)
	return _c
}

// SetOriginalRcpt sets the "original_rcpt" field.
func (_c *MailboxMessageCreate) SetOriginalRcpt(v string) *MailboxMessageCreate {
	_c.mutation.SetOriginalRcpt(v)
	return _c
}

// SetBaseRcpt sets the "base_rcpt" field.
func (_c *MailboxMessageCreate) SetBaseRcpt(v string) *MailboxMessageCreate {
	_c.mutation.SetBaseRcpt(v)
	return _c
}

// SetPlusTag sets the "plus_tag" field.
func (_c *MailboxMessageCreate) SetPlusTag(v string) *MailboxMessageCreate {
	_c.mutation.SetPlusTag(v)
	return _c
}

// SetNillablePlusTag sets the "plus_tag" field if the given value is not nil.
func (_c *MailboxMessageCreate) SetNillablePlusTag(v *string) *MailboxMessageCreate {
	if v != nil {
		_c.SetPlusTag(*v)
	}
	return _c
}

// SetResolvedRouteID sets the "resolved_route_id" field.
func (_c *MailboxMessageCreate) SetResolvedRouteID(v string) *MailboxMessageCreate {
	_c.mutation.SetResolvedRouteID(v)
	return _c
}

// SetNillableResolvedRouteID sets the "resolved_route_id" field if the given value is not nil.
func (_c *MailboxMessageCreate) SetNillableResolvedRouteID(v *string) *MailboxMessageCreate {
	if v != nil {
		_c.SetResolvedRouteID(*v)
	}
	return _c
}

// SetRead sets the "read" field.
func (_c *MailboxMessageCreate) SetRead(v bool) *MailboxMessageCreate {
	_c.mutation.SetRead(v)
	return _c
}

// SetNillableRead sets the "read" field if the given value is not nil.
func (_c *MailboxMessageCreate) SetNillableRead(v *bool) *MailboxMessageCreate {
	if v != nil {
		_c.SetRead(*v)
	}
	return _c
}

// SetFlagged sets the "flagged" field.
func (_c *MailboxMessageCreate) SetFlagged(v bool) *MailboxMessageCreate {
	_c.mutation.SetFlagged(v)
	return _c
}

// SetNillableFlagged sets the "flagged" field if the given value is not nil.
func (_c *MailboxMessageCreate) SetNillableFlagged(v *bool) *MailboxMessageCreate {
	if v != nil {
		_c.SetFlagged(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MailboxMessageCreate) SetCreatedAt(v time.Time) *MailboxMessageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MailboxMessageCreate) SetNillableCreatedAt(v *time.Time) *MailboxMessageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MailboxMessageCreate) SetUpdatedAt(v time.Time) *MailboxMessageCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MailboxMessageCreate) SetNillableUpdatedAt(v *time.Time) *MailboxMessageCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *MailboxMessageCreate) SetDeletedAt(v time.Time) *MailboxMessageCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *MailboxMessageCreate) SetNillableDeletedAt(v *time.Time) *MailboxMessageCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MailboxMessageCreate) SetID(v string) *MailboxMessageCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *MailboxMessageCreate) SetNillableID(v *string) *MailboxMessageCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the MailboxMessageMutation object of the builder.
func (_c *MailboxMessageCreate) Mutation() *MailboxMessageMutation {
	return _c.mutation
}

// Save creates the MailboxMessage in the database.
func (_c *MailboxMessageCreate) Save(ctx context.Context) (*MailboxMessage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MailboxMessageCreate) SaveX(ctx context.Context) *MailboxMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MailboxMessageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MailboxMessageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MailboxMessageCreate) defaults() {
	if _, ok := _c.mutation.Read(); !ok {
		v := mailboxmessage.DefaultRead
		_c.mutation.SetRead(v)
	}
	if _, ok := _c.mutation.Flagged(); !ok {
		v := mailboxmessage.DefaultFlagged
		_c.mutation.SetFlagged(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := mailboxmessage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := mailboxmessage.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := mailboxmessage.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MailboxMessageCreate) check() error {
	if _, ok := _c.mutation.MailboxID(); !ok {
		return &ValidationError{Name: "mailbox_id", err: errors.New(`ent: missing required field "MailboxMessage.mailbox_id"`)}
	}
	if _, ok := _c.mutation.MessageID(); !ok {
		return &ValidationError{Name: "message_id", err: errors.New(`ent: missing required field "MailboxMessage.message_id"`)}
	}
	if _, ok := _c.mutation.FolderID(); !ok {
		return &ValidationError{Name: "folder_id", err: errors.New(`ent: missing required field "MailboxMessage.folder_id"`)}
	}
	if _, ok := _c.mutation.OriginalRcpt(); !ok {
		return &ValidationError{Name: "original_rcpt", err: errors.New(`ent: missing required field "MailboxMessage.original_rcpt"`)}
	}
	if _, ok := _c.mutation.BaseRcpt(); !ok {
		return &ValidationError{Name: "base_rcpt", err: errors.New(`ent: missing required field "MailboxMessage.base_rcpt"`)}
	}
	if _, ok := _c.mutation.Read(); !ok {
		return &ValidationError{Name: "read", err: errors.New(`ent: missing required field "MailboxMessage.read"`)}
	}
	if _, ok := _c.mutation.Flagged(); !ok {
		return &ValidationError{Name: "flagged", err: errors.New(`ent: missing required field "MailboxMessage.flagged"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MailboxMessage.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "MailboxMessage.updated_at"`)}
	}
	return nil
}

func (_c *MailboxMessageCreate) sqlSave(ctx context.Context) (*MailboxMessage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected MailboxMessage.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MailboxMessageCreate) createSpec() (*MailboxMessage, *sqlgraph.CreateSpec) {
	var (
		_node = &MailboxMessage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mailboxmessage.Table, sqlgraph.NewFieldSpec(mailboxmessage.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.MailboxID(); ok {
		_spec.SetField(mailboxmessage.FieldMailboxID, field.TypeString, value)
		_node.MailboxID = value
	}
	if value, ok := _c.mutation.MessageID(); ok {
		_spec.SetField(mailboxmessage.FieldMessageID, field.TypeString, value)
		_node.MessageID = value
	}
	if value, ok := _c.mutation.FolderID(); ok {
		_spec.SetField(mailboxmessage.FieldFolderID, field.TypeString, value)
		_node.FolderID = value
	}
	if value, ok := _c.mutation.OriginalRcpt(); ok {
		_spec.SetField(mailboxmessage.FieldOriginalRcpt, field.TypeString, value)
		_node.OriginalRcpt = value
	}
	if value, ok := _c.mutation.BaseRcpt(); ok {
		_spec.SetField(mailboxmessage.FieldBaseRcpt, field.TypeString, value)
		_node.BaseRcpt = value
	}
	if value, ok := _c.mutation.PlusTag(); ok {
		_spec.SetField(mailboxmessage.FieldPlusTag, field.TypeString, value)
		_node.PlusTag = value
	}
	if value, ok := _c.mutation.ResolvedRouteID(); ok {
		_spec.SetField(mailboxmessage.FieldResolvedRouteID, field.TypeString, value)
		_node.ResolvedRouteID = value
	}
	if value, ok := _c.mutation.Read(); ok {
		_spec.SetField(mailboxmessage.FieldRead, field.TypeBool, value)
		_node.Read = value
	}
	if value, ok := _c.mutation.Flagged(); ok {
		_spec.SetField(mailboxmessage.FieldFlagged, field.TypeBool, value)
		_node.Flagged = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(mailboxmessage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(mailboxmessage.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(mailboxmessage.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	return _node, _spec
}

// MailboxMessageCreateBulk is the builder for creating many MailboxMessage entities in bulk.
type MailboxMessageCreateBulk struct {
	config
	err      error
	builders []*MailboxMessageCreate
}

// Save creates the MailboxMessage entities in the database.
func (_c *MailboxMessageCreateBulk) Save(ctx context.Context) ([]*MailboxMessage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MailboxMessage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MailboxMessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MailboxMessageCreateBulk) SaveX(ctx context.Context) []*MailboxMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MailboxMessageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MailboxMessageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
