// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zephyraoss/haitatsu/internal/database/ent/outboundattempt"
)

// OutboundAttemptCreate is the builder for creating a OutboundAttempt entity.
type OutboundAttemptCreate struct {
	config
	mutation *OutboundAttemptMutation
	hooks    []Hook
}

// SetOutboundJobID sets the "outbound_job_id" field.
func (_c *OutboundAttemptCreate) SetOutboundJobID(v string) *OutboundAttemptCreate {
	_c.mutation.SetOutboundJobID(v)
	return _c
}

// SetMessageID sets the "message_id" field.
func (_c *OutboundAttemptCreate) SetMessageID(v string) *OutboundAttemptCreate {
	_c.mutation.SetMessageID(v)
	return _c
}

// SetSMTPCode sets the "smtp_code" field.
func (_c *OutboundAttemptCreate) SetSMTPCode(v int) *OutboundAttemptCreate {
	_c.mutation.SetSMTPCode(v)
	return _c
}

// SetNillableSMTPCode sets the "smtp_code" field if the given value is not nil.
func (_c *OutboundAttemptCreate) SetNillableSMTPCode(v *int) *OutboundAttemptCreate {
	if v != nil {
		_c.SetSMTPCode(*v)
	}
	return _c
}

// SetEnhancedStatusCode sets the "enhanced_status_code" field.
func (_c *OutboundAttemptCreate) SetEnhancedStatusCode(v string) *OutboundAttemptCreate {
	_c.mutation.SetEnhancedStatusCode(v)
	return _c
}

// SetNillableEnhancedStatusCode sets the "enhanced_status_code" field if the given value is not nil.
func (_c *OutboundAttemptCreate) SetNillableEnhancedStatusCode(v *string) *OutboundAttemptCreate {
	if v != nil {
		_c.SetEnhancedStatusCode(*v)
	}
	return _c
}

// SetClassification sets the "classification" field.
func (_c *OutboundAttemptCreate) SetClassification(v string) *OutboundAttemptCreate {
	_c.mutation.SetClassification(v)
	return _c
}

// SetResponse sets the "response" field.
func (_c *OutboundAttemptCreate) SetResponse(v string) *OutboundAttemptCreate {
	_c.mutation.SetResponse(v)
	return _c
}

// SetNillableResponse sets the "response" field if the given value is not nil.
func (_c *OutboundAttemptCreate) SetNillableResponse(v *string) *OutboundAttemptCreate {
	if v != nil {
		_c.SetResponse(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OutboundAttemptCreate) SetCreatedAt(v time.Time) *OutboundAttemptCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OutboundAttemptCreate) SetNillableCreatedAt(v *time.Time) *OutboundAttemptCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OutboundAttemptCreate) SetID(v string) *OutboundAttemptCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *OutboundAttemptCreate) SetNillableID(v *string) *OutboundAttemptCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the OutboundAttemptMutation object of the builder.
func (_c *OutboundAttemptCreate) Mutation() *OutboundAttemptMutation {
	return _c.mutation
}

// Save creates the OutboundAttempt in the database.
func (_c *OutboundAttemptCreate) Save(ctx context.Context) (*OutboundAttempt, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OutboundAttemptCreate) SaveX(ctx context.Context) *OutboundAttempt {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OutboundAttemptCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OutboundAttemptCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OutboundAttemptCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := outboundattempt.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := outboundattempt.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OutboundAttemptCreate) check() error {
	if _, ok := _c.mutation.OutboundJobID(); !ok {
		return &ValidationError{Name: "outbound_job_id", err: errors.New(`ent: missing required field "OutboundAttempt.outbound_job_id"`)}
	}
	if _, ok := _c.mutation.MessageID(); !ok {
		return &ValidationError{Name: "message_id", err: errors.New(`ent: missing required field "OutboundAttempt.message_id"`)}
	}
	if _, ok := _c.mutation.Classification(); !ok {
		return &ValidationError{Name: "classification", err: errors.New(`ent: missing required field "OutboundAttempt.classification"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OutboundAttempt.created_at"`)}
	}
	return nil
}

func (_c *OutboundAttemptCreate) sqlSave(ctx context.Context) (*OutboundAttempt, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected OutboundAttempt.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OutboundAttemptCreate) createSpec() (*OutboundAttempt, *sqlgraph.CreateSpec) {
	var (
		_node = &OutboundAttempt{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(outboundattempt.Table, sqlgraph.NewFieldSpec(outboundattempt.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.OutboundJobID(); ok {
		_spec.SetField(outboundattempt.FieldOutboundJobID, field.TypeString, value)
		_node.OutboundJobID = value
	}
	if value, ok := _c.mutation.MessageID(); ok {
		_spec.SetField(outboundattempt.FieldMessageID, field.TypeString, value)
		_node.MessageID = value
	}
	if value, ok := _c.mutation.SMTPCode(); ok {
		_spec.SetField(outboundattempt.FieldSMTPCode, field.TypeInt, value)
		_node.SMTPCode = value
	}
	if value, ok := _c.mutation.EnhancedStatusCode(); ok {
		_spec.SetField(outboundattempt.FieldEnhancedStatusCode, field.TypeString, value)
		_node.EnhancedStatusCode = value
	}
	if value, ok := _c.mutation.Classification(); ok {
		_spec.SetField(outboundattempt.FieldClassification, field.TypeString, value)
		_node.Classification = value
	}
	if value, ok := _c.mutation.Response(); ok {
		_spec.SetField(outboundattempt.FieldResponse, field.TypeString, value)
		_node.Response = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(outboundattempt.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OutboundAttemptCreateBulk is the builder for creating many OutboundAttempt entities in bulk.
type OutboundAttemptCreateBulk struct {
	config
	err      error
	builders []*OutboundAttemptCreate
}

// Save creates the OutboundAttempt entities in the database.
func (_c *OutboundAttemptCreateBulk) Save(ctx context.Context) ([]*OutboundAttempt, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OutboundAttempt, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OutboundAttemptMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OutboundAttemptCreateBulk) SaveX(ctx context.Context) []*OutboundAttempt {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OutboundAttemptCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OutboundAttemptCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
