// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zephyraoss/haitatsu/internal/database/ent/outboundjob"
	"github.com/zephyraoss/haitatsu/internal/database/ent/predicate"
)

// OutboundJobUpdate is the builder for updating OutboundJob entities.
type OutboundJobUpdate struct {
	config
	hooks    []Hook
	mutation *OutboundJobMutation
}

// Where appends a list predicates to the OutboundJobUpdate builder.
func (_u *OutboundJobUpdate) Where(ps ...predicate.OutboundJob) *OutboundJobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMailboxID sets the "mailbox_id" field.
func (_u *OutboundJobUpdate) SetMailboxID(v string) *OutboundJobUpdate {
	_u.mutation.SetMailboxID(v)
	return _u
}

// SetNillableMailboxID sets the "mailbox_id" field if the given value is not nil.
func (_u *OutboundJobUpdate) SetNillableMailboxID(v *string) *OutboundJobUpdate {
	if v != nil {
		_u.SetMailboxID(*v)
	}
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *OutboundJobUpdate) SetMessageID(v string) *OutboundJobUpdate {
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *OutboundJobUpdate) SetNillableMessageID(v *string) *OutboundJobUpdate {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *OutboundJobUpdate) SetStatus(v string) *OutboundJobUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OutboundJobUpdate) SetNillableStatus(v *string) *OutboundJobUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *OutboundJobUpdate) SetAttempts(v int) *OutboundJobUpdate {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *OutboundJobUpdate) SetNillableAttempts(v *int) *OutboundJobUpdate {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *OutboundJobUpdate) AddAttempts(v int) *OutboundJobUpdate {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetLockedBy sets the "locked_by" field.
func (_u *OutboundJobUpdate) SetLockedBy(v string) *OutboundJobUpdate {
	_u.mutation.SetLockedBy(v)
	return _u
}

// SetNillableLockedBy sets the "locked_by" field if the given value is not nil.
func (_u *OutboundJobUpdate) SetNillableLockedBy(v *string) *OutboundJobUpdate {
	if v != nil {
		_u.SetLockedBy(*v)
	}
	return _u
}

// ClearLockedBy clears the value of the "locked_by" field.
func (_u *OutboundJobUpdate) ClearLockedBy() *OutboundJobUpdate {
	_u.mutation.ClearLockedBy()
	return _u
}

// SetLockedUntil sets the "locked_until" field.
func (_u *OutboundJobUpdate) SetLockedUntil(v time.Time) *OutboundJobUpdate {
	_u.mutation.SetLockedUntil(v)
	return _u
}

// SetNillableLockedUntil sets the "locked_until" field if the given value is not nil.
func (_u *OutboundJobUpdate) SetNillableLockedUntil(v *time.Time) *OutboundJobUpdate {
	if v != nil {
		_u.SetLockedUntil(*v)
	}
	return _u
}

// ClearLockedUntil clears the value of the "locked_until" field.
func (_u *OutboundJobUpdate) ClearLockedUntil() *OutboundJobUpdate {
	_u.mutation.ClearLockedUntil()
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *OutboundJobUpdate) SetNextAttemptAt(v time.Time) *OutboundJobUpdate {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *OutboundJobUpdate) SetNillableNextAttemptAt(v *time.Time) *OutboundJobUpdate {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (_u *OutboundJobUpdate) ClearNextAttemptAt() *OutboundJobUpdate {
	_u.mutation.ClearNextAttemptAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *OutboundJobUpdate) SetLastError(v map[string]interface{}) *OutboundJobUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *OutboundJobUpdate) ClearLastError() *OutboundJobUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OutboundJobUpdate) SetUpdatedAt(v time.Time) *OutboundJobUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the OutboundJobMutation object of the builder.
func (_u *OutboundJobUpdate) Mutation() *OutboundJobMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OutboundJobUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OutboundJobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OutboundJobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OutboundJobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OutboundJobUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := outboundjob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *OutboundJobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(outboundjob.Table, outboundjob.Columns, sqlgraph.NewFieldSpec(outboundjob.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MailboxID(); ok {
		_spec.SetField(outboundjob.FieldMailboxID, field.TypeString, value)
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(outboundjob.FieldMessageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(outboundjob.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(outboundjob.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(outboundjob.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LockedBy(); ok {
		_spec.SetField(outboundjob.FieldLockedBy, field.TypeString, value)
	}
	if _u.mutation.LockedByCleared() {
		_spec.ClearField(outboundjob.FieldLockedBy, field.TypeString)
	}
	if value, ok := _u.mutation.LockedUntil(); ok {
		_spec.SetField(outboundjob.FieldLockedUntil, field.TypeTime, value)
	}
	if _u.mutation.LockedUntilCleared() {
		_spec.ClearField(outboundjob.FieldLockedUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(outboundjob.FieldNextAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.NextAttemptAtCleared() {
		_spec.ClearField(outboundjob.FieldNextAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(outboundjob.FieldLastError, field.TypeJSON, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(outboundjob.FieldLastError, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(outboundjob.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{outboundjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OutboundJobUpdateOne is the builder for updating a single OutboundJob entity.
type OutboundJobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OutboundJobMutation
}

// SetMailboxID sets the "mailbox_id" field.
func (_u *OutboundJobUpdateOne) SetMailboxID(v string) *OutboundJobUpdateOne {
	_u.mutation.SetMailboxID(v)
	return _u
}

// SetNillableMailboxID sets the "mailbox_id" field if the given value is not nil.
func (_u *OutboundJobUpdateOne) SetNillableMailboxID(v *string) *OutboundJobUpdateOne {
	if v != nil {
		_u.SetMailboxID(*v)
	}
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *OutboundJobUpdateOne) SetMessageID(v string) *OutboundJobUpdateOne {
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *OutboundJobUpdateOne) SetNillableMessageID(v *string) *OutboundJobUpdateOne {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *OutboundJobUpdateOne) SetStatus(v string) *OutboundJobUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OutboundJobUpdateOne) SetNillableStatus(v *string) *OutboundJobUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *OutboundJobUpdateOne) SetAttempts(v int) *OutboundJobUpdateOne {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *OutboundJobUpdateOne) SetNillableAttempts(v *int) *OutboundJobUpdateOne {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *OutboundJobUpdateOne) AddAttempts(v int) *OutboundJobUpdateOne {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetLockedBy sets the "locked_by" field.
func (_u *OutboundJobUpdateOne) SetLockedBy(v string) *OutboundJobUpdateOne {
	_u.mutation.SetLockedBy(v)
	return _u
}

// SetNillableLockedBy sets the "locked_by" field if the given value is not nil.
func (_u *OutboundJobUpdateOne) SetNillableLockedBy(v *string) *OutboundJobUpdateOne {
	if v != nil {
		_u.SetLockedBy(*v)
	}
	return _u
}

// ClearLockedBy clears the value of the "locked_by" field.
func (_u *OutboundJobUpdateOne) ClearLockedBy() *OutboundJobUpdateOne {
	_u.mutation.ClearLockedBy()
	return _u
}

// SetLockedUntil sets the "locked_until" field.
func (_u *OutboundJobUpdateOne) SetLockedUntil(v time.Time) *OutboundJobUpdateOne {
	_u.mutation.SetLockedUntil(v)
	return _u
}

// SetNillableLockedUntil sets the "locked_until" field if the given value is not nil.
func (_u *OutboundJobUpdateOne) SetNillableLockedUntil(v *time.Time) *OutboundJobUpdateOne {
	if v != nil {
		_u.SetLockedUntil(*v)
	}
	return _u
}

// ClearLockedUntil clears the value of the "locked_until" field.
func (_u *OutboundJobUpdateOne) ClearLockedUntil() *OutboundJobUpdateOne {
	_u.mutation.ClearLockedUntil()
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *OutboundJobUpdateOne) SetNextAttemptAt(v time.Time) *OutboundJobUpdateOne {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *OutboundJobUpdateOne) SetNillableNextAttemptAt(v *time.Time) *OutboundJobUpdateOne {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (_u *OutboundJobUpdateOne) ClearNextAttemptAt() *OutboundJobUpdateOne {
	_u.mutation.ClearNextAttemptAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *OutboundJobUpdateOne) SetLastError(v map[string]interface{}) *OutboundJobUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *OutboundJobUpdateOne) ClearLastError() *OutboundJobUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OutboundJobUpdateOne) SetUpdatedAt(v time.Time) *OutboundJobUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the OutboundJobMutation object of the builder.
func (_u *OutboundJobUpdateOne) Mutation() *OutboundJobMutation {
	return _u.mutation
}

// Where appends a list predicates to the OutboundJobUpdate builder.
func (_u *OutboundJobUpdateOne) Where(ps ...predicate.OutboundJob) *OutboundJobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OutboundJobUpdateOne) Select(field string, fields ...string) *OutboundJobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OutboundJob entity.
func (_u *OutboundJobUpdateOne) Save(ctx context.Context) (*OutboundJob, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OutboundJobUpdateOne) SaveX(ctx context.Context) *OutboundJob {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OutboundJobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OutboundJobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OutboundJobUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := outboundjob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *OutboundJobUpdateOne) sqlSave(ctx context.Context) (_node *OutboundJob, err error) {
	_spec := sqlgraph.NewUpdateSpec(outboundjob.Table, outboundjob.Columns, sqlgraph.NewFieldSpec(outboundjob.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OutboundJob.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, outboundjob.FieldID)
		for _, f := range fields {
			if !outboundjob.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != outboundjob.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MailboxID(); ok {
		_spec.SetField(outboundjob.FieldMailboxID, field.TypeString, value)
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(outboundjob.FieldMessageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(outboundjob.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(outboundjob.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(outboundjob.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LockedBy(); ok {
		_spec.SetField(outboundjob.FieldLockedBy, field.TypeString, value)
	}
	if _u.mutation.LockedByCleared() {
		_spec.ClearField(outboundjob.FieldLockedBy, field.TypeString)
	}
	if value, ok := _u.mutation.LockedUntil(); ok {
		_spec.SetField(outboundjob.FieldLockedUntil, field.TypeTime, value)
	}
	if _u.mutation.LockedUntilCleared() {
		_spec.ClearField(outboundjob.FieldLockedUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(outboundjob.FieldNextAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.NextAttemptAtCleared() {
		_spec.ClearField(outboundjob.FieldNextAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(outboundjob.FieldLastError, field.TypeJSON, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(outboundjob.FieldLastError, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(outboundjob.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &OutboundJob{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{outboundjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
