// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zephyraoss/haitatsu/internal/database/ent/routingrule"
)

// RoutingRuleCreate is the builder for creating a RoutingRule entity.
type RoutingRuleCreate struct {
	config
	mutation *RoutingRuleMutation
	hooks    []Hook
}

// SetScope sets the "scope" field.
func (_c *RoutingRuleCreate) SetScope(v string) *RoutingRuleCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetScopeRef sets the "scope_ref" field.
func (_c *RoutingRuleCreate) SetScopeRef(v string) *RoutingRuleCreate {
	_c.mutation.SetScopeRef(v)
	return _c
}

// SetNillableScopeRef sets the "scope_ref" field if the given value is not nil.
func (_c *RoutingRuleCreate) SetNillableScopeRef(v *string) *RoutingRuleCreate {
	if v != nil {
		_c.SetScopeRef(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *RoutingRuleCreate) SetPriority(v int) *RoutingRuleCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *RoutingRuleCreate) SetNillablePriority(v *int) *RoutingRuleCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *RoutingRuleCreate) SetName(v string) *RoutingRuleCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *RoutingRuleCreate) SetEnabled(v bool) *RoutingRuleCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *RoutingRuleCreate) SetNillableEnabled(v *bool) *RoutingRuleCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetConditions sets the "conditions" field.
func (_c *RoutingRuleCreate) SetConditions(v map[string]interface{}) *RoutingRuleCreate {
	_c.mutation.SetConditions(v)
	return _c
}

// SetActions sets the "actions" field.
func (_c *RoutingRuleCreate) SetActions(v []map[string]interface{}) *RoutingRuleCreate {
	_c.mutation.SetActions(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RoutingRuleCreate) SetCreatedAt(v time.Time) *RoutingRuleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RoutingRuleCreate) SetNillableCreatedAt(v *time.Time) *RoutingRuleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RoutingRuleCreate) SetUpdatedAt(v time.Time) *RoutingRuleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RoutingRuleCreate) SetNillableUpdatedAt(v *time.Time) *RoutingRuleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RoutingRuleCreate) SetID(v string) *RoutingRuleCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *RoutingRuleCreate) SetNillableID(v *string) *RoutingRuleCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the RoutingRuleMutation object of the builder.
func (_c *RoutingRuleCreate) Mutation() *RoutingRuleMutation {
	return _c.mutation
}

// Save creates the RoutingRule in the database.
func (_c *RoutingRuleCreate) Save(ctx context.Context) (*RoutingRule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RoutingRuleCreate) SaveX(ctx context.Context) *RoutingRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RoutingRuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RoutingRuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RoutingRuleCreate) defaults() {
	if _, ok := _c.mutation.Priority(); !ok {
		v := routingrule.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := routingrule.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := routingrule.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := routingrule.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := routingrule.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RoutingRuleCreate) check() error {
	if _, ok := _c.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "RoutingRule.scope"`)}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "RoutingRule.priority"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "RoutingRule.name"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "RoutingRule.enabled"`)}
	}
	if _, ok := _c.mutation.Conditions(); !ok {
		return &ValidationError{Name: "conditions", err: errors.New(`ent: missing required field "RoutingRule.conditions"`)}
	}
	if _, ok := _c.mutation.Actions(); !ok {
		return &ValidationError{Name: "actions", err: errors.New(`ent: missing required field "RoutingRule.actions"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RoutingRule.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RoutingRule.updated_at"`)}
	}
	return nil
}

func (_c *RoutingRuleCreate) sqlSave(ctx context.Context) (*RoutingRule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected RoutingRule.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RoutingRuleCreate) createSpec() (*RoutingRule, *sqlgraph.CreateSpec) {
	var (
		_node = &RoutingRule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(routingrule.Table, sqlgraph.NewFieldSpec(routingrule.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(routingrule.FieldScope, field.TypeString, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.ScopeRef(); ok {
		_spec.SetField(routingrule.FieldScopeRef, field.TypeString, value)
		_node.ScopeRef = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(routingrule.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(routingrule.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(routingrule.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Conditions(); ok {
		_spec.SetField(routingrule.FieldConditions, field.TypeJSON, value)
		_node.Conditions = value
	}
	if value, ok := _c.mutation.Actions(); ok {
		_spec.SetField(routingrule.FieldActions, field.TypeJSON, value)
		_node.Actions = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(routingrule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(routingrule.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// RoutingRuleCreateBulk is the builder for creating many RoutingRule entities in bulk.
type RoutingRuleCreateBulk struct {
	config
	err      error
	builders []*RoutingRuleCreate
}

// Save creates the RoutingRule entities in the database.
func (_c *RoutingRuleCreateBulk) Save(ctx context.Context) ([]*RoutingRule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RoutingRule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RoutingRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RoutingRuleCreateBulk) SaveX(ctx context.Context) []*RoutingRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RoutingRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RoutingRuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
