// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/zephyraoss/haitatsu/internal/database/ent/predicate"
	"github.com/zephyraoss/haitatsu/internal/database/ent/routingrule"
)

// RoutingRuleUpdate is the builder for updating RoutingRule entities.
type RoutingRuleUpdate struct {
	config
	hooks    []Hook
	mutation *RoutingRuleMutation
}

// Where appends a list predicates to the RoutingRuleUpdate builder.
func (_u *RoutingRuleUpdate) Where(ps ...predicate.RoutingRule) *RoutingRuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetScope sets the "scope" field.
func (_u *RoutingRuleUpdate) SetScope(v string) *RoutingRuleUpdate {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *RoutingRuleUpdate) SetNillableScope(v *string) *RoutingRuleUpdate {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetScopeRef sets the "scope_ref" field.
func (_u *RoutingRuleUpdate) SetScopeRef(v string) *RoutingRuleUpdate {
	_u.mutation.SetScopeRef(v)
	return _u
}

// SetNillableScopeRef sets the "scope_ref" field if the given value is not nil.
func (_u *RoutingRuleUpdate) SetNillableScopeRef(v *string) *RoutingRuleUpdate {
	if v != nil {
		_u.SetScopeRef(*v)
	}
	return _u
}

// ClearScopeRef clears the value of the "scope_ref" field.
func (_u *RoutingRuleUpdate) ClearScopeRef() *RoutingRuleUpdate {
	_u.mutation.ClearScopeRef()
	return _u
}

// SetPriority sets the "priority" field.
func (_u *RoutingRuleUpdate) SetPriority(v int) *RoutingRuleUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *RoutingRuleUpdate) SetNillablePriority(v *int) *RoutingRuleUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *RoutingRuleUpdate) AddPriority(v int) *RoutingRuleUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetName sets the "name" field.
func (_u *RoutingRuleUpdate) SetName(v string) *RoutingRuleUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RoutingRuleUpdate) SetNillableName(v *string) *RoutingRuleUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *RoutingRuleUpdate) SetEnabled(v bool) *RoutingRuleUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *RoutingRuleUpdate) SetNillableEnabled(v *bool) *RoutingRuleUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetConditions sets the "conditions" field.
func (_u *RoutingRuleUpdate) SetConditions(v map[string]interface{}) *RoutingRuleUpdate {
	_u.mutation.SetConditions(v)
	return _u
}

// SetActions sets the "actions" field.
func (_u *RoutingRuleUpdate) SetActions(v []map[string]interface{}) *RoutingRuleUpdate {
	_u.mutation.SetActions(v)
	return _u
}

// AppendActions appends value to the "actions" field.
func (_u *RoutingRuleUpdate) AppendActions(v []map[string]interface{}) *RoutingRuleUpdate {
	_u.mutation.AppendActions(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RoutingRuleUpdate) SetUpdatedAt(v time.Time) *RoutingRuleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the RoutingRuleMutation object of the builder.
func (_u *RoutingRuleUpdate) Mutation() *RoutingRuleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RoutingRuleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RoutingRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RoutingRuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RoutingRuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RoutingRuleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := routingrule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *RoutingRuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(routingrule.Table, routingrule.Columns, sqlgraph.NewFieldSpec(routingrule.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(routingrule.FieldScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScopeRef(); ok {
		_spec.SetField(routingrule.FieldScopeRef, field.TypeString, value)
	}
	if _u.mutation.ScopeRefCleared() {
		_spec.ClearField(routingrule.FieldScopeRef, field.TypeString)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(routingrule.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(routingrule.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(routingrule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(routingrule.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Conditions(); ok {
		_spec.SetField(routingrule.FieldConditions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Actions(); ok {
		_spec.SetField(routingrule.FieldActions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedActions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, routingrule.FieldActions, value)
		})
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(routingrule.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{routingrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RoutingRuleUpdateOne is the builder for updating a single RoutingRule entity.
type RoutingRuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RoutingRuleMutation
}

// SetScope sets the "scope" field.
func (_u *RoutingRuleUpdateOne) SetScope(v string) *RoutingRuleUpdateOne {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *RoutingRuleUpdateOne) SetNillableScope(v *string) *RoutingRuleUpdateOne {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetScopeRef sets the "scope_ref" field.
func (_u *RoutingRuleUpdateOne) SetScopeRef(v string) *RoutingRuleUpdateOne {
	_u.mutation.SetScopeRef(v)
	return _u
}

// SetNillableScopeRef sets the "scope_ref" field if the given value is not nil.
func (_u *RoutingRuleUpdateOne) SetNillableScopeRef(v *string) *RoutingRuleUpdateOne {
	if v != nil {
		_u.SetScopeRef(*v)
	}
	return _u
}

// ClearScopeRef clears the value of the "scope_ref" field.
func (_u *RoutingRuleUpdateOne) ClearScopeRef() *RoutingRuleUpdateOne {
	_u.mutation.ClearScopeRef()
	return _u
}

// SetPriority sets the "priority" field.
func (_u *RoutingRuleUpdateOne) SetPriority(v int) *RoutingRuleUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *RoutingRuleUpdateOne) SetNillablePriority(v *int) *RoutingRuleUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *RoutingRuleUpdateOne) AddPriority(v int) *RoutingRuleUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetName sets the "name" field.
func (_u *RoutingRuleUpdateOne) SetName(v string) *RoutingRuleUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RoutingRuleUpdateOne) SetNillableName(v *string) *RoutingRuleUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *RoutingRuleUpdateOne) SetEnabled(v bool) *RoutingRuleUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *RoutingRuleUpdateOne) SetNillableEnabled(v *bool) *RoutingRuleUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetConditions sets the "conditions" field.
func (_u *RoutingRuleUpdateOne) SetConditions(v map[string]interface{}) *RoutingRuleUpdateOne {
	_u.mutation.SetConditions(v)
	return _u
}

// SetActions sets the "actions" field.
func (_u *RoutingRuleUpdateOne) SetActions(v []map[string]interface{}) *RoutingRuleUpdateOne {
	_u.mutation.SetActions(v)
	return _u
}

// AppendActions appends value to the "actions" field.
func (_u *RoutingRuleUpdateOne) AppendActions(v []map[string]interface{}) *RoutingRuleUpdateOne {
	_u.mutation.AppendActions(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RoutingRuleUpdateOne) SetUpdatedAt(v time.Time) *RoutingRuleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the RoutingRuleMutation object of the builder.
func (_u *RoutingRuleUpdateOne) Mutation() *RoutingRuleMutation {
	return _u.mutation
}

// Where appends a list predicates to the RoutingRuleUpdate builder.
func (_u *RoutingRuleUpdateOne) Where(ps ...predicate.RoutingRule) *RoutingRuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RoutingRuleUpdateOne) Select(field string, fields ...string) *RoutingRuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RoutingRule entity.
func (_u *RoutingRuleUpdateOne) Save(ctx context.Context) (*RoutingRule, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RoutingRuleUpdateOne) SaveX(ctx context.Context) *RoutingRule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RoutingRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RoutingRuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RoutingRuleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := routingrule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *RoutingRuleUpdateOne) sqlSave(ctx context.Context) (_node *RoutingRule, err error) {
	_spec := sqlgraph.NewUpdateSpec(routingrule.Table, routingrule.Columns, sqlgraph.NewFieldSpec(routingrule.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RoutingRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, routingrule.FieldID)
		for _, f := range fields {
			if !routingrule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != routingrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(routingrule.FieldScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScopeRef(); ok {
		_spec.SetField(routingrule.FieldScopeRef, field.TypeString, value)
	}
	if _u.mutation.ScopeRefCleared() {
		_spec.ClearField(routingrule.FieldScopeRef, field.TypeString)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(routingrule.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(routingrule.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(routingrule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(routingrule.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Conditions(); ok {
		_spec.SetField(routingrule.FieldConditions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Actions(); ok {
		_spec.SetField(routingrule.FieldActions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedActions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, routingrule.FieldActions, value)
		})
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(routingrule.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &RoutingRule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{routingrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
