// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zephyraoss/haitatsu/internal/database/ent/predicate"
	"github.com/zephyraoss/haitatsu/internal/database/ent/schemamigration"
)

// SchemaMigrationUpdate is the builder for updating SchemaMigration entities.
type SchemaMigrationUpdate struct {
	config
	hooks    []Hook
	mutation *SchemaMigrationMutation
}

// Where appends a list predicates to the SchemaMigrationUpdate builder.
func (_u *SchemaMigrationUpdate) Where(ps ...predicate.SchemaMigration) *SchemaMigrationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAppliedAt sets the "applied_at" field.
func (_u *SchemaMigrationUpdate) SetAppliedAt(v time.Time) *SchemaMigrationUpdate {
	_u.mutation.SetAppliedAt(v)
	return _u
}

// SetNillableAppliedAt sets the "applied_at" field if the given value is not nil.
func (_u *SchemaMigrationUpdate) SetNillableAppliedAt(v *time.Time) *SchemaMigrationUpdate {
	if v != nil {
		_u.SetAppliedAt(*v)
	}
	return _u
}

// Mutation returns the SchemaMigrationMutation object of the builder.
func (_u *SchemaMigrationUpdate) Mutation() *SchemaMigrationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SchemaMigrationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SchemaMigrationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SchemaMigrationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SchemaMigrationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SchemaMigrationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(schemamigration.Table, schemamigration.Columns, sqlgraph.NewFieldSpec(schemamigration.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AppliedAt(); ok {
		_spec.SetField(schemamigration.FieldAppliedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{schemamigration.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SchemaMigrationUpdateOne is the builder for updating a single SchemaMigration entity.
type SchemaMigrationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SchemaMigrationMutation
}

// SetAppliedAt sets the "applied_at" field.
func (_u *SchemaMigrationUpdateOne) SetAppliedAt(v time.Time) *SchemaMigrationUpdateOne {
	_u.mutation.SetAppliedAt(v)
	return _u
}

// SetNillableAppliedAt sets the "applied_at" field if the given value is not nil.
func (_u *SchemaMigrationUpdateOne) SetNillableAppliedAt(v *time.Time) *SchemaMigrationUpdateOne {
	if v != nil {
		_u.SetAppliedAt(*v)
	}
	return _u
}

// Mutation returns the SchemaMigrationMutation object of the builder.
func (_u *SchemaMigrationUpdateOne) Mutation() *SchemaMigrationMutation {
	return _u.mutation
}

// Where appends a list predicates to the SchemaMigrationUpdate builder.
func (_u *SchemaMigrationUpdateOne) Where(ps ...predicate.SchemaMigration) *SchemaMigrationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SchemaMigrationUpdateOne) Select(field string, fields ...string) *SchemaMigrationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SchemaMigration entity.
func (_u *SchemaMigrationUpdateOne) Save(ctx context.Context) (*SchemaMigration, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SchemaMigrationUpdateOne) SaveX(ctx context.Context) *SchemaMigration {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SchemaMigrationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SchemaMigrationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SchemaMigrationUpdateOne) sqlSave(ctx context.Context) (_node *SchemaMigration, err error) {
	_spec := sqlgraph.NewUpdateSpec(schemamigration.Table, schemamigration.Columns, sqlgraph.NewFieldSpec(schemamigration.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SchemaMigration.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, schemamigration.FieldID)
		for _, f := range fields {
			if !schemamigration.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != schemamigration.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AppliedAt(); ok {
		_spec.SetField(schemamigration.FieldAppliedAt, field.TypeTime, value)
	}
	_node = &SchemaMigration{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{schemamigration.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
