// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zephyraoss/haitatsu/internal/database/ent/predicate"
	"github.com/zephyraoss/haitatsu/internal/database/ent/senderrule"
)

// SenderRuleUpdate is the builder for updating SenderRule entities.
type SenderRuleUpdate struct {
	config
	hooks    []Hook
	mutation *SenderRuleMutation
}

// Where appends a list predicates to the SenderRuleUpdate builder.
func (_u *SenderRuleUpdate) Where(ps ...predicate.SenderRule) *SenderRuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetScope sets the "scope" field.
func (_u *SenderRuleUpdate) SetScope(v string) *SenderRuleUpdate {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *SenderRuleUpdate) SetNillableScope(v *string) *SenderRuleUpdate {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetScopeRef sets the "scope_ref" field.
func (_u *SenderRuleUpdate) SetScopeRef(v string) *SenderRuleUpdate {
	_u.mutation.SetScopeRef(v)
	return _u
}

// SetNillableScopeRef sets the "scope_ref" field if the given value is not nil.
func (_u *SenderRuleUpdate) SetNillableScopeRef(v *string) *SenderRuleUpdate {
	if v != nil {
		_u.SetScopeRef(*v)
	}
	return _u
}

// ClearScopeRef clears the value of the "scope_ref" field.
func (_u *SenderRuleUpdate) ClearScopeRef() *SenderRuleUpdate {
	_u.mutation.ClearScopeRef()
	return _u
}

// SetKind sets the "kind" field.
func (_u *SenderRuleUpdate) SetKind(v string) *SenderRuleUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *SenderRuleUpdate) SetNillableKind(v *string) *SenderRuleUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetMatchType sets the "match_type" field.
func (_u *SenderRuleUpdate) SetMatchType(v string) *SenderRuleUpdate {
	_u.mutation.SetMatchType(v)
	return _u
}

// SetNillableMatchType sets the "match_type" field if the given value is not nil.
func (_u *SenderRuleUpdate) SetNillableMatchType(v *string) *SenderRuleUpdate {
	if v != nil {
		_u.SetMatchType(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *SenderRuleUpdate) SetValue(v string) *SenderRuleUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *SenderRuleUpdate) SetNillableValue(v *string) *SenderRuleUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *SenderRuleUpdate) SetAction(v string) *SenderRuleUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *SenderRuleUpdate) SetNillableAction(v *string) *SenderRuleUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SenderRuleUpdate) SetUpdatedAt(v time.Time) *SenderRuleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SenderRuleMutation object of the builder.
func (_u *SenderRuleUpdate) Mutation() *SenderRuleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SenderRuleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SenderRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SenderRuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SenderRuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SenderRuleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := senderrule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *SenderRuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(senderrule.Table, senderrule.Columns, sqlgraph.NewFieldSpec(senderrule.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(senderrule.FieldScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScopeRef(); ok {
		_spec.SetField(senderrule.FieldScopeRef, field.TypeString, value)
	}
	if _u.mutation.ScopeRefCleared() {
		_spec.ClearField(senderrule.FieldScopeRef, field.TypeString)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(senderrule.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.MatchType(); ok {
		_spec.SetField(senderrule.FieldMatchType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(senderrule.FieldValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(senderrule.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(senderrule.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{senderrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SenderRuleUpdateOne is the builder for updating a single SenderRule entity.
type SenderRuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SenderRuleMutation
}

// SetScope sets the "scope" field.
func (_u *SenderRuleUpdateOne) SetScope(v string) *SenderRuleUpdateOne {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *SenderRuleUpdateOne) SetNillableScope(v *string) *SenderRuleUpdateOne {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetScopeRef sets the "scope_ref" field.
func (_u *SenderRuleUpdateOne) SetScopeRef(v string) *SenderRuleUpdateOne {
	_u.mutation.SetScopeRef(v)
	return _u
}

// SetNillableScopeRef sets the "scope_ref" field if the given value is not nil.
func (_u *SenderRuleUpdateOne) SetNillableScopeRef(v *string) *SenderRuleUpdateOne {
	if v != nil {
		_u.SetScopeRef(*v)
	}
	return _u
}

// ClearScopeRef clears the value of the "scope_ref" field.
func (_u *SenderRuleUpdateOne) ClearScopeRef() *SenderRuleUpdateOne {
	_u.mutation.ClearScopeRef()
	return _u
}

// SetKind sets the "kind" field.
func (_u *SenderRuleUpdateOne) SetKind(v string) *SenderRuleUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *SenderRuleUpdateOne) SetNillableKind(v *string) *SenderRuleUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetMatchType sets the "match_type" field.
func (_u *SenderRuleUpdateOne) SetMatchType(v string) *SenderRuleUpdateOne {
	_u.mutation.SetMatchType(v)
	return _u
}

// SetNillableMatchType sets the "match_type" field if the given value is not nil.
func (_u *SenderRuleUpdateOne) SetNillableMatchType(v *string) *SenderRuleUpdateOne {
	if v != nil {
		_u.SetMatchType(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *SenderRuleUpdateOne) SetValue(v string) *SenderRuleUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *SenderRuleUpdateOne) SetNillableValue(v *string) *SenderRuleUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *SenderRuleUpdateOne) SetAction(v string) *SenderRuleUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *SenderRuleUpdateOne) SetNillableAction(v *string) *SenderRuleUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SenderRuleUpdateOne) SetUpdatedAt(v time.Time) *SenderRuleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SenderRuleMutation object of the builder.
func (_u *SenderRuleUpdateOne) Mutation() *SenderRuleMutation {
	return _u.mutation
}

// Where appends a list predicates to the SenderRuleUpdate builder.
func (_u *SenderRuleUpdateOne) Where(ps ...predicate.SenderRule) *SenderRuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SenderRuleUpdateOne) Select(field string, fields ...string) *SenderRuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SenderRule entity.
func (_u *SenderRuleUpdateOne) Save(ctx context.Context) (*SenderRule, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SenderRuleUpdateOne) SaveX(ctx context.Context) *SenderRule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SenderRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SenderRuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SenderRuleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := senderrule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *SenderRuleUpdateOne) sqlSave(ctx context.Context) (_node *SenderRule, err error) {
	_spec := sqlgraph.NewUpdateSpec(senderrule.Table, senderrule.Columns, sqlgraph.NewFieldSpec(senderrule.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SenderRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, senderrule.FieldID)
		for _, f := range fields {
			if !senderrule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != senderrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(senderrule.FieldScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScopeRef(); ok {
		_spec.SetField(senderrule.FieldScopeRef, field.TypeString, value)
	}
	if _u.mutation.ScopeRefCleared() {
		_spec.ClearField(senderrule.FieldScopeRef, field.TypeString)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(senderrule.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.MatchType(); ok {
		_spec.SetField(senderrule.FieldMatchType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(senderrule.FieldValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(senderrule.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(senderrule.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &SenderRule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{senderrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
