// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zephyraoss/haitatsu/internal/database/ent/senderrule"
)

// SenderRuleCreate is the builder for creating a SenderRule entity.
type SenderRuleCreate struct {
	config
	mutation *SenderRuleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetScope sets the "scope" field.
func (_c *SenderRuleCreate) SetScope(v string) *SenderRuleCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetScopeRef sets the "scope_ref" field.
func (_c *SenderRuleCreate) SetScopeRef(v string) *SenderRuleCreate {
	_c.mutation.SetScopeRef(v)
	return _c
}

// SetNillableScopeRef sets the "scope_ref" field if the given value is not nil.
func (_c *SenderRuleCreate) SetNillableScopeRef(v *string) *SenderRuleCreate {
	if v != nil {
		_c.SetScopeRef(*v)
	}
	return _c
}

// SetKind sets the "kind" field.
func (_c *SenderRuleCreate) SetKind(v string) *SenderRuleCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetMatchType sets the "match_type" field.
func (_c *SenderRuleCreate) SetMatchType(v string) *SenderRuleCreate {
	_c.mutation.SetMatchType(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *SenderRuleCreate) SetValue(v string) *SenderRuleCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetAction sets the "action" field.
func (_c *SenderRuleCreate) SetAction(v string) *SenderRuleCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_c *SenderRuleCreate) SetNillableAction(v *string) *SenderRuleCreate {
	if v != nil {
		_c.SetAction(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SenderRuleCreate) SetCreatedAt(v time.Time) *SenderRuleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SenderRuleCreate) SetNillableCreatedAt(v *time.Time) *SenderRuleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SenderRuleCreate) SetUpdatedAt(v time.Time) *SenderRuleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SenderRuleCreate) SetNillableUpdatedAt(v *time.Time) *SenderRuleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SenderRuleCreate) SetID(v string) *SenderRuleCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SenderRuleCreate) SetNillableID(v *string) *SenderRuleCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the SenderRuleMutation object of the builder.
func (_c *SenderRuleCreate) Mutation() *SenderRuleMutation {
	return _c.mutation
}

// Save creates the SenderRule in the database.
func (_c *SenderRuleCreate) Save(ctx context.Context) (*SenderRule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SenderRuleCreate) SaveX(ctx context.Context) *SenderRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SenderRuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SenderRuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SenderRuleCreate) defaults() {
	if _, ok := _c.mutation.Action(); !ok {
		v := senderrule.DefaultAction
		_c.mutation.SetAction(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := senderrule.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := senderrule.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := senderrule.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SenderRuleCreate) check() error {
	if _, ok := _c.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "SenderRule.scope"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "SenderRule.kind"`)}
	}
	if _, ok := _c.mutation.MatchType(); !ok {
		return &ValidationError{Name: "match_type", err: errors.New(`ent: missing required field "SenderRule.match_type"`)}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "SenderRule.value"`)}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "SenderRule.action"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SenderRule.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SenderRule.updated_at"`)}
	}
	return nil
}

func (_c *SenderRuleCreate) sqlSave(ctx context.Context) (*SenderRule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected SenderRule.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SenderRuleCreate) createSpec() (*SenderRule, *sqlgraph.CreateSpec) {
	var (
		_node = &SenderRule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(senderrule.Table, sqlgraph.NewFieldSpec(senderrule.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(senderrule.FieldScope, field.TypeString, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.ScopeRef(); ok {
		_spec.SetField(senderrule.FieldScopeRef, field.TypeString, value)
		_node.ScopeRef = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(senderrule.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.MatchType(); ok {
		_spec.SetField(senderrule.FieldMatchType, field.TypeString, value)
		_node.MatchType = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(senderrule.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(senderrule.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(senderrule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(senderrule.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SenderRule.Create().
//		SetScope(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SenderRuleUpsert) {
//			SetScope(v+v).
//		}).
//		Exec(ctx)
func (_c *SenderRuleCreate) OnConflict(opts ...sql.ConflictOption) *SenderRuleUpsertOne {
	_c.conflict = opts
	return &SenderRuleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SenderRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SenderRuleCreate) OnConflictColumns(columns ...string) *SenderRuleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SenderRuleUpsertOne{
		create: _c,
	}
}

type (
	// SenderRuleUpsertOne is the builder for "upsert"-ing
	//  one SenderRule node.
	SenderRuleUpsertOne struct {
		create *SenderRuleCreate
	}

	// SenderRuleUpsert is the "OnConflict" setter.
	SenderRuleUpsert struct {
		*sql.UpdateSet
	}
)

// SetScope sets the "scope" field.
func (u *SenderRuleUpsert) SetScope(v string) *SenderRuleUpsert {
	u.Set(senderrule.FieldScope, v)
	return u
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *SenderRuleUpsert) UpdateScope() *SenderRuleUpsert {
	u.SetExcluded(senderrule.FieldScope)
	return u
}

// SetScopeRef sets the "scope_ref" field.
func (u *SenderRuleUpsert) SetScopeRef(v string) *SenderRuleUpsert {
	u.Set(senderrule.FieldScopeRef, v)
	return u
}

// UpdateScopeRef sets the "scope_ref" field to the value that was provided on create.
func (u *SenderRuleUpsert) UpdateScopeRef() *SenderRuleUpsert {
	u.SetExcluded(senderrule.FieldScopeRef)
	return u
}

// ClearScopeRef clears the value of the "scope_ref" field.
func (u *SenderRuleUpsert) ClearScopeRef() *SenderRuleUpsert {
	u.SetNull(senderrule.FieldScopeRef)
	return u
}

// SetKind sets the "kind" field.
func (u *SenderRuleUpsert) SetKind(v string) *SenderRuleUpsert {
	u.Set(senderrule.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *SenderRuleUpsert) UpdateKind() *SenderRuleUpsert {
	u.SetExcluded(senderrule.FieldKind)
	return u
}

// SetMatchType sets the "match_type" field.
func (u *SenderRuleUpsert) SetMatchType(v string) *SenderRuleUpsert {
	u.Set(senderrule.FieldMatchType, v)
	return u
}

// UpdateMatchType sets the "match_type" field to the value that was provided on create.
func (u *SenderRuleUpsert) UpdateMatchType() *SenderRuleUpsert {
	u.SetExcluded(senderrule.FieldMatchType)
	return u
}

// SetValue sets the "value" field.
func (u *SenderRuleUpsert) SetValue(v string) *SenderRuleUpsert {
	u.Set(senderrule.FieldValue, v)
	return u
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *SenderRuleUpsert) UpdateValue() *SenderRuleUpsert {
	u.SetExcluded(senderrule.FieldValue)
	return u
}

// SetAction sets the "action" field.
func (u *SenderRuleUpsert) SetAction(v string) *SenderRuleUpsert {
	u.Set(senderrule.FieldAction, v)
	return u
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *SenderRuleUpsert) UpdateAction() *SenderRuleUpsert {
	u.SetExcluded(senderrule.FieldAction)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SenderRuleUpsert) SetUpdatedAt(v time.Time) *SenderRuleUpsert {
	u.Set(senderrule.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SenderRuleUpsert) UpdateUpdatedAt() *SenderRuleUpsert {
	u.SetExcluded(senderrule.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.SenderRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(senderrule.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SenderRuleUpsertOne) UpdateNewValues() *SenderRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(senderrule.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(senderrule.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SenderRule.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SenderRuleUpsertOne) Ignore() *SenderRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SenderRuleUpsertOne) DoNothing() *SenderRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SenderRuleCreate.OnConflict
// documentation for more info.
func (u *SenderRuleUpsertOne) Update(set func(*SenderRuleUpsert)) *SenderRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SenderRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetScope sets the "scope" field.
func (u *SenderRuleUpsertOne) SetScope(v string) *SenderRuleUpsertOne {
	return u.Update(func(s *SenderRuleUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *SenderRuleUpsertOne) UpdateScope() *SenderRuleUpsertOne {
	return u.Update(func(s *SenderRuleUpsert) {
		s.UpdateScope()
	})
}

// SetScopeRef sets the "scope_ref" field.
func (u *SenderRuleUpsertOne) SetScopeRef(v string) *SenderRuleUpsertOne {
	return u.Update(func(s *SenderRuleUpsert) {
		s.SetScopeRef(v)
	})
}

// UpdateScopeRef sets the "scope_ref" field to the value that was provided on create.
func (u *SenderRuleUpsertOne) UpdateScopeRef() *SenderRuleUpsertOne {
	return u.Update(func(s *SenderRuleUpsert) {
		s.UpdateScopeRef()
	})
}

// ClearScopeRef clears the value of the "scope_ref" field.
func (u *SenderRuleUpsertOne) ClearScopeRef() *SenderRuleUpsertOne {
	return u.Update(func(s *SenderRuleUpsert) {
		s.ClearScopeRef()
	})
}

// SetKind sets the "kind" field.
func (u *SenderRuleUpsertOne) SetKind(v string) *SenderRuleUpsertOne {
	return u.Update(func(s *SenderRuleUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *SenderRuleUpsertOne) UpdateKind() *SenderRuleUpsertOne {
	return u.Update(func(s *SenderRuleUpsert) {
		s.UpdateKind()
	})
}

// SetMatchType sets the "match_type" field.
func (u *SenderRuleUpsertOne) SetMatchType(v string) *SenderRuleUpsertOne {
	return u.Update(func(s *SenderRuleUpsert) {
		s.SetMatchType(v)
	})
}

// UpdateMatchType sets the "match_type" field to the value that was provided on create.
func (u *SenderRuleUpsertOne) UpdateMatchType() *SenderRuleUpsertOne {
	return u.Update(func(s *SenderRuleUpsert) {
		s.UpdateMatchType()
	})
}

// SetValue sets the "value" field.
func (u *SenderRuleUpsertOne) SetValue(v string) *SenderRuleUpsertOne {
	return u.Update(func(s *SenderRuleUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *SenderRuleUpsertOne) UpdateValue() *SenderRuleUpsertOne {
	return u.Update(func(s *SenderRuleUpsert) {
		s.UpdateValue()
	})
}

// SetAction sets the "action" field.
func (u *SenderRuleUpsertOne) SetAction(v string) *SenderRuleUpsertOne {
	return u.Update(func(s *SenderRuleUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *SenderRuleUpsertOne) UpdateAction() *SenderRuleUpsertOne {
	return u.Update(func(s *SenderRuleUpsert) {
		s.UpdateAction()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SenderRuleUpsertOne) SetUpdatedAt(v time.Time) *SenderRuleUpsertOne {
	return u.Update(func(s *SenderRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SenderRuleUpsertOne) UpdateUpdatedAt() *SenderRuleUpsertOne {
	return u.Update(func(s *SenderRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SenderRuleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SenderRuleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SenderRuleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SenderRuleUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: SenderRuleUpsertOne.ID is not supported by MySQL driver. Use SenderRuleUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SenderRuleUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SenderRuleCreateBulk is the builder for creating many SenderRule entities in bulk.
type SenderRuleCreateBulk struct {
	config
	err      error
	builders []*SenderRuleCreate
	conflict []sql.ConflictOption
}

// Save creates the SenderRule entities in the database.
func (_c *SenderRuleCreateBulk) Save(ctx context.Context) ([]*SenderRule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SenderRule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SenderRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SenderRuleCreateBulk) SaveX(ctx context.Context) []*SenderRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SenderRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SenderRuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SenderRule.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SenderRuleUpsert) {
//			SetScope(v+v).
//		}).
//		Exec(ctx)
func (_c *SenderRuleCreateBulk) OnConflict(opts ...sql.ConflictOption) *SenderRuleUpsertBulk {
	_c.conflict = opts
	return &SenderRuleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SenderRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SenderRuleCreateBulk) OnConflictColumns(columns ...string) *SenderRuleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SenderRuleUpsertBulk{
		create: _c,
	}
}

// SenderRuleUpsertBulk is the builder for "upsert"-ing
// a bulk of SenderRule nodes.
type SenderRuleUpsertBulk struct {
	create *SenderRuleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SenderRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(senderrule.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SenderRuleUpsertBulk) UpdateNewValues() *SenderRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(senderrule.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(senderrule.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SenderRule.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SenderRuleUpsertBulk) Ignore() *SenderRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SenderRuleUpsertBulk) DoNothing() *SenderRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SenderRuleCreateBulk.OnConflict
// documentation for more info.
func (u *SenderRuleUpsertBulk) Update(set func(*SenderRuleUpsert)) *SenderRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SenderRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetScope sets the "scope" field.
func (u *SenderRuleUpsertBulk) SetScope(v string) *SenderRuleUpsertBulk {
	return u.Update(func(s *SenderRuleUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *SenderRuleUpsertBulk) UpdateScope() *SenderRuleUpsertBulk {
	return u.Update(func(s *SenderRuleUpsert) {
		s.UpdateScope()
	})
}

// SetScopeRef sets the "scope_ref" field.
func (u *SenderRuleUpsertBulk) SetScopeRef(v string) *SenderRuleUpsertBulk {
	return u.Update(func(s *SenderRuleUpsert) {
		s.SetScopeRef(v)
	})
}

// UpdateScopeRef sets the "scope_ref" field to the value that was provided on create.
func (u *SenderRuleUpsertBulk) UpdateScopeRef() *SenderRuleUpsertBulk {
	return u.Update(func(s *SenderRuleUpsert) {
		s.UpdateScopeRef()
	})
}

// ClearScopeRef clears the value of the "scope_ref" field.
func (u *SenderRuleUpsertBulk) ClearScopeRef() *SenderRuleUpsertBulk {
	return u.Update(func(s *SenderRuleUpsert) {
		s.ClearScopeRef()
	})
}

// SetKind sets the "kind" field.
func (u *SenderRuleUpsertBulk) SetKind(v string) *SenderRuleUpsertBulk {
	return u.Update(func(s *SenderRuleUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *SenderRuleUpsertBulk) UpdateKind() *SenderRuleUpsertBulk {
	return u.Update(func(s *SenderRuleUpsert) {
		s.UpdateKind()
	})
}

// SetMatchType sets the "match_type" field.
func (u *SenderRuleUpsertBulk) SetMatchType(v string) *SenderRuleUpsertBulk {
	return u.Update(func(s *SenderRuleUpsert) {
		s.SetMatchType(v)
	})
}

// UpdateMatchType sets the "match_type" field to the value that was provided on create.
func (u *SenderRuleUpsertBulk) UpdateMatchType() *SenderRuleUpsertBulk {
	return u.Update(func(s *SenderRuleUpsert) {
		s.UpdateMatchType()
	})
}

// SetValue sets the "value" field.
func (u *SenderRuleUpsertBulk) SetValue(v string) *SenderRuleUpsertBulk {
	return u.Update(func(s *SenderRuleUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *SenderRuleUpsertBulk) UpdateValue() *SenderRuleUpsertBulk {
	return u.Update(func(s *SenderRuleUpsert) {
		s.UpdateValue()
	})
}

// SetAction sets the "action" field.
func (u *SenderRuleUpsertBulk) SetAction(v string) *SenderRuleUpsertBulk {
	return u.Update(func(s *SenderRuleUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *SenderRuleUpsertBulk) UpdateAction() *SenderRuleUpsertBulk {
	return u.Update(func(s *SenderRuleUpsert) {
		s.UpdateAction()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SenderRuleUpsertBulk) SetUpdatedAt(v time.Time) *SenderRuleUpsertBulk {
	return u.Update(func(s *SenderRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SenderRuleUpsertBulk) UpdateUpdatedAt() *SenderRuleUpsertBulk {
	return u.Update(func(s *SenderRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SenderRuleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SenderRuleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SenderRuleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SenderRuleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
