// Code generated by ent, DO NOT EDIT.

package apppassword

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/zephyraoss/haitatsu/internal/database/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldContainsFold(FieldID, id))
}

// MailboxID applies equality check predicate on the "mailbox_id" field. It's identical to MailboxIDEQ.
func MailboxID(v string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldEQ(FieldMailboxID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldEQ(FieldName, v))
}

// Hash applies equality check predicate on the "hash" field. It's identical to HashEQ.
func Hash(v string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldEQ(FieldHash, v))
}

// LastUsedAt applies equality check predicate on the "last_used_at" field. It's identical to LastUsedAtEQ.
func LastUsedAt(v time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldEQ(FieldLastUsedAt, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldEQ(FieldRevokedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldEQ(FieldDeletedAt, v))
}

// MailboxIDEQ applies the EQ predicate on the "mailbox_id" field.
func MailboxIDEQ(v string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldEQ(FieldMailboxID, v))
}

// MailboxIDNEQ applies the NEQ predicate on the "mailbox_id" field.
func MailboxIDNEQ(v string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldNEQ(FieldMailboxID, v))
}

// MailboxIDIn applies the In predicate on the "mailbox_id" field.
func MailboxIDIn(vs ...string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldIn(FieldMailboxID, vs...))
}

// MailboxIDNotIn applies the NotIn predicate on the "mailbox_id" field.
func MailboxIDNotIn(vs ...string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldNotIn(FieldMailboxID, vs...))
}

// MailboxIDGT applies the GT predicate on the "mailbox_id" field.
func MailboxIDGT(v string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldGT(FieldMailboxID, v))
}

// MailboxIDGTE applies the GTE predicate on the "mailbox_id" field.
func MailboxIDGTE(v string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldGTE(FieldMailboxID, v))
}

// MailboxIDLT applies the LT predicate on the "mailbox_id" field.
func MailboxIDLT(v string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldLT(FieldMailboxID, v))
}

// MailboxIDLTE applies the LTE predicate on the "mailbox_id" field.
func MailboxIDLTE(v string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldLTE(FieldMailboxID, v))
}

// MailboxIDContains applies the Contains predicate on the "mailbox_id" field.
func MailboxIDContains(v string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldContains(FieldMailboxID, v))
}

// MailboxIDHasPrefix applies the HasPrefix predicate on the "mailbox_id" field.
func MailboxIDHasPrefix(v string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldHasPrefix(FieldMailboxID, v))
}

// MailboxIDHasSuffix applies the HasSuffix predicate on the "mailbox_id" field.
func MailboxIDHasSuffix(v string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldHasSuffix(FieldMailboxID, v))
}

// MailboxIDEqualFold applies the EqualFold predicate on the "mailbox_id" field.
func MailboxIDEqualFold(v string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldEqualFold(FieldMailboxID, v))
}

// MailboxIDContainsFold applies the ContainsFold predicate on the "mailbox_id" field.
func MailboxIDContainsFold(v string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldContainsFold(FieldMailboxID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldContainsFold(FieldName, v))
}

// HashEQ applies the EQ predicate on the "hash" field.
func HashEQ(v string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldEQ(FieldHash, v))
}

// HashNEQ applies the NEQ predicate on the "hash" field.
func HashNEQ(v string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldNEQ(FieldHash, v))
}

// HashIn applies the In predicate on the "hash" field.
func HashIn(vs ...string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldIn(FieldHash, vs...))
}

// HashNotIn applies the NotIn predicate on the "hash" field.
func HashNotIn(vs ...string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldNotIn(FieldHash, vs...))
}

// HashGT applies the GT predicate on the "hash" field.
func HashGT(v string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldGT(FieldHash, v))
}

// HashGTE applies the GTE predicate on the "hash" field.
func HashGTE(v string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldGTE(FieldHash, v))
}

// HashLT applies the LT predicate on the "hash" field.
func HashLT(v string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldLT(FieldHash, v))
}

// HashLTE applies the LTE predicate on the "hash" field.
func HashLTE(v string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldLTE(FieldHash, v))
}

// HashContains applies the Contains predicate on the "hash" field.
func HashContains(v string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldContains(FieldHash, v))
}

// HashHasPrefix applies the HasPrefix predicate on the "hash" field.
func HashHasPrefix(v string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldHasPrefix(FieldHash, v))
}

// HashHasSuffix applies the HasSuffix predicate on the "hash" field.
func HashHasSuffix(v string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldHasSuffix(FieldHash, v))
}

// HashEqualFold applies the EqualFold predicate on the "hash" field.
func HashEqualFold(v string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldEqualFold(FieldHash, v))
}

// HashContainsFold applies the ContainsFold predicate on the "hash" field.
func HashContainsFold(v string) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldContainsFold(FieldHash, v))
}

// LastUsedAtEQ applies the EQ predicate on the "last_used_at" field.
func LastUsedAtEQ(v time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastUsedAtNEQ applies the NEQ predicate on the "last_used_at" field.
func LastUsedAtNEQ(v time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldNEQ(FieldLastUsedAt, v))
}

// LastUsedAtIn applies the In predicate on the "last_used_at" field.
func LastUsedAtIn(vs ...time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldIn(FieldLastUsedAt, vs...))
}

// LastUsedAtNotIn applies the NotIn predicate on the "last_used_at" field.
func LastUsedAtNotIn(vs ...time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldNotIn(FieldLastUsedAt, vs...))
}

// LastUsedAtGT applies the GT predicate on the "last_used_at" field.
func LastUsedAtGT(v time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldGT(FieldLastUsedAt, v))
}

// LastUsedAtGTE applies the GTE predicate on the "last_used_at" field.
func LastUsedAtGTE(v time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldGTE(FieldLastUsedAt, v))
}

// LastUsedAtLT applies the LT predicate on the "last_used_at" field.
func LastUsedAtLT(v time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldLT(FieldLastUsedAt, v))
}

// LastUsedAtLTE applies the LTE predicate on the "last_used_at" field.
func LastUsedAtLTE(v time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldLTE(FieldLastUsedAt, v))
}

// LastUsedAtIsNil applies the IsNil predicate on the "last_used_at" field.
func LastUsedAtIsNil() predicate.AppPassword {
	return predicate.AppPassword(sql.FieldIsNull(FieldLastUsedAt))
}

// LastUsedAtNotNil applies the NotNil predicate on the "last_used_at" field.
func LastUsedAtNotNil() predicate.AppPassword {
	return predicate.AppPassword(sql.FieldNotNull(FieldLastUsedAt))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.AppPassword {
	return predicate.AppPassword(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.AppPassword {
	return predicate.AppPassword(sql.FieldNotNull(FieldRevokedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.AppPassword {
	return predicate.AppPassword(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.AppPassword {
	return predicate.AppPassword(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.AppPassword {
	return predicate.AppPassword(sql.FieldNotNull(FieldDeletedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AppPassword) predicate.AppPassword {
	return predicate.AppPassword(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AppPassword) predicate.AppPassword {
	return predicate.AppPassword(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AppPassword) predicate.AppPassword {
	return predicate.AppPassword(sql.NotPredicates(p))
}
