// Code generated by ent, DO NOT EDIT.

package mailboxmessage

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the mailboxmessage type in the database.
	Label = "mailbox_message"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMailboxID holds the string denoting the mailbox_id field in the database.
	FieldMailboxID = "mailbox_id"
	// FieldMessageID holds the string denoting the message_id field in the database.
	FieldMessageID = "message_id"
	// FieldFolderID holds the string denoting the folder_id field in the database.
	FieldFolderID = "folder_id"
	// FieldOriginalRcpt holds the string denoting the original_rcpt field in the database.
	FieldOriginalRcpt = "original_rcpt"
	// FieldBaseRcpt holds the string denoting the base_rcpt field in the database.
	FieldBaseRcpt = "base_rcpt"
	// FieldPlusTag holds the string denoting the plus_tag field in the database.
	FieldPlusTag = "plus_tag"
	// FieldResolvedRouteID holds the string denoting the resolved_route_id field in the database.
	FieldResolvedRouteID = "resolved_route_id"
	// FieldRead holds the string denoting the read field in the database.
	FieldRead = "read"
	// FieldFlagged holds the string denoting the flagged field in the database.
	FieldFlagged = "flagged"
	// FieldImapDeleted holds the string denoting the imap_deleted field in the database.
	FieldImapDeleted = "imap_deleted"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// Table holds the table name of the mailboxmessage in the database.
	Table = "mailbox_messages"
)

// Columns holds all SQL columns for mailboxmessage fields.
var Columns = []string{
	FieldID,
	FieldMailboxID,
	FieldMessageID,
	FieldFolderID,
	FieldOriginalRcpt,
	FieldBaseRcpt,
	FieldPlusTag,
	FieldResolvedRouteID,
	FieldRead,
	FieldFlagged,
	FieldImapDeleted,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRead holds the default value on creation for the "read" field.
	DefaultRead bool
	// DefaultFlagged holds the default value on creation for the "flagged" field.
	DefaultFlagged bool
	// DefaultImapDeleted holds the default value on creation for the "imap_deleted" field.
	DefaultImapDeleted bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the MailboxMessage queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByMailboxID orders the results by the mailbox_id field.
func ByMailboxID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMailboxID, opts...).ToFunc()
}

// ByMessageID orders the results by the message_id field.
func ByMessageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMessageID, opts...).ToFunc()
}

// ByFolderID orders the results by the folder_id field.
func ByFolderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFolderID, opts...).ToFunc()
}

// ByOriginalRcpt orders the results by the original_rcpt field.
func ByOriginalRcpt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOriginalRcpt, opts...).ToFunc()
}

// ByBaseRcpt orders the results by the base_rcpt field.
func ByBaseRcpt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseRcpt, opts...).ToFunc()
}

// ByPlusTag orders the results by the plus_tag field.
func ByPlusTag(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlusTag, opts...).ToFunc()
}

// ByResolvedRouteID orders the results by the resolved_route_id field.
func ByResolvedRouteID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResolvedRouteID, opts...).ToFunc()
}

// ByRead orders the results by the read field.
func ByRead(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRead, opts...).ToFunc()
}

// ByFlagged orders the results by the flagged field.
func ByFlagged(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFlagged, opts...).ToFunc()
}

// ByImapDeleted orders the results by the imap_deleted field.
func ByImapDeleted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImapDeleted, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}
