// Code generated by ent, DO NOT EDIT.

package mailboxmessagelabel

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the mailboxmessagelabel type in the database.
	Label = "mailbox_message_label"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMailboxMessageID holds the string denoting the mailbox_message_id field in the database.
	FieldMailboxMessageID = "mailbox_message_id"
	// FieldLabelID holds the string denoting the label_id field in the database.
	FieldLabelID = "label_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the mailboxmessagelabel in the database.
	Table = "mailbox_message_labels"
)

// Columns holds all SQL columns for mailboxmessagelabel fields.
var Columns = []string{
	FieldID,
	FieldMailboxMessageID,
	FieldLabelID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the MailboxMessageLabel queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByMailboxMessageID orders the results by the mailbox_message_id field.
func ByMailboxMessageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMailboxMessageID, opts...).ToFunc()
}

// ByLabelID orders the results by the label_id field.
func ByLabelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLabelID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
