// Code generated by ent, DO NOT EDIT.

package mailboxmessagelabel

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/zephyraoss/haitatsu/internal/database/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldContainsFold(FieldID, id))
}

// MailboxMessageID applies equality check predicate on the "mailbox_message_id" field. It's identical to MailboxMessageIDEQ.
func MailboxMessageID(v string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldEQ(FieldMailboxMessageID, v))
}

// LabelID applies equality check predicate on the "label_id" field. It's identical to LabelIDEQ.
func LabelID(v string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldEQ(FieldLabelID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldEQ(FieldCreatedAt, v))
}

// MailboxMessageIDEQ applies the EQ predicate on the "mailbox_message_id" field.
func MailboxMessageIDEQ(v string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldEQ(FieldMailboxMessageID, v))
}

// MailboxMessageIDNEQ applies the NEQ predicate on the "mailbox_message_id" field.
func MailboxMessageIDNEQ(v string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldNEQ(FieldMailboxMessageID, v))
}

// MailboxMessageIDIn applies the In predicate on the "mailbox_message_id" field.
func MailboxMessageIDIn(vs ...string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldIn(FieldMailboxMessageID, vs...))
}

// MailboxMessageIDNotIn applies the NotIn predicate on the "mailbox_message_id" field.
func MailboxMessageIDNotIn(vs ...string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldNotIn(FieldMailboxMessageID, vs...))
}

// MailboxMessageIDGT applies the GT predicate on the "mailbox_message_id" field.
func MailboxMessageIDGT(v string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldGT(FieldMailboxMessageID, v))
}

// MailboxMessageIDGTE applies the GTE predicate on the "mailbox_message_id" field.
func MailboxMessageIDGTE(v string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldGTE(FieldMailboxMessageID, v))
}

// MailboxMessageIDLT applies the LT predicate on the "mailbox_message_id" field.
func MailboxMessageIDLT(v string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldLT(FieldMailboxMessageID, v))
}

// MailboxMessageIDLTE applies the LTE predicate on the "mailbox_message_id" field.
func MailboxMessageIDLTE(v string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldLTE(FieldMailboxMessageID, v))
}

// MailboxMessageIDContains applies the Contains predicate on the "mailbox_message_id" field.
func MailboxMessageIDContains(v string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldContains(FieldMailboxMessageID, v))
}

// MailboxMessageIDHasPrefix applies the HasPrefix predicate on the "mailbox_message_id" field.
func MailboxMessageIDHasPrefix(v string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldHasPrefix(FieldMailboxMessageID, v))
}

// MailboxMessageIDHasSuffix applies the HasSuffix predicate on the "mailbox_message_id" field.
func MailboxMessageIDHasSuffix(v string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldHasSuffix(FieldMailboxMessageID, v))
}

// MailboxMessageIDEqualFold applies the EqualFold predicate on the "mailbox_message_id" field.
func MailboxMessageIDEqualFold(v string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldEqualFold(FieldMailboxMessageID, v))
}

// MailboxMessageIDContainsFold applies the ContainsFold predicate on the "mailbox_message_id" field.
func MailboxMessageIDContainsFold(v string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldContainsFold(FieldMailboxMessageID, v))
}

// LabelIDEQ applies the EQ predicate on the "label_id" field.
func LabelIDEQ(v string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldEQ(FieldLabelID, v))
}

// LabelIDNEQ applies the NEQ predicate on the "label_id" field.
func LabelIDNEQ(v string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldNEQ(FieldLabelID, v))
}

// LabelIDIn applies the In predicate on the "label_id" field.
func LabelIDIn(vs ...string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldIn(FieldLabelID, vs...))
}

// LabelIDNotIn applies the NotIn predicate on the "label_id" field.
func LabelIDNotIn(vs ...string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldNotIn(FieldLabelID, vs...))
}

// LabelIDGT applies the GT predicate on the "label_id" field.
func LabelIDGT(v string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldGT(FieldLabelID, v))
}

// LabelIDGTE applies the GTE predicate on the "label_id" field.
func LabelIDGTE(v string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldGTE(FieldLabelID, v))
}

// LabelIDLT applies the LT predicate on the "label_id" field.
func LabelIDLT(v string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldLT(FieldLabelID, v))
}

// LabelIDLTE applies the LTE predicate on the "label_id" field.
func LabelIDLTE(v string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldLTE(FieldLabelID, v))
}

// LabelIDContains applies the Contains predicate on the "label_id" field.
func LabelIDContains(v string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldContains(FieldLabelID, v))
}

// LabelIDHasPrefix applies the HasPrefix predicate on the "label_id" field.
func LabelIDHasPrefix(v string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldHasPrefix(FieldLabelID, v))
}

// LabelIDHasSuffix applies the HasSuffix predicate on the "label_id" field.
func LabelIDHasSuffix(v string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldHasSuffix(FieldLabelID, v))
}

// LabelIDEqualFold applies the EqualFold predicate on the "label_id" field.
func LabelIDEqualFold(v string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldEqualFold(FieldLabelID, v))
}

// LabelIDContainsFold applies the ContainsFold predicate on the "label_id" field.
func LabelIDContainsFold(v string) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldContainsFold(FieldLabelID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MailboxMessageLabel) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MailboxMessageLabel) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MailboxMessageLabel) predicate.MailboxMessageLabel {
	return predicate.MailboxMessageLabel(sql.NotPredicates(p))
}
