// Code generated by ent, DO NOT EDIT.

package message

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the message type in the database.
	Label = "message"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTraceID holds the string denoting the trace_id field in the database.
	FieldTraceID = "trace_id"
	// FieldRfcMessageID holds the string denoting the rfc_message_id field in the database.
	FieldRfcMessageID = "rfc_message_id"
	// FieldBlobKey holds the string denoting the blob_key field in the database.
	FieldBlobKey = "blob_key"
	// FieldSha256 holds the string denoting the sha256 field in the database.
	FieldSha256 = "sha256"
	// FieldSizeBytes holds the string denoting the size_bytes field in the database.
	FieldSizeBytes = "size_bytes"
	// FieldHeaders holds the string denoting the headers field in the database.
	FieldHeaders = "headers"
	// FieldFromAddresses holds the string denoting the from_addresses field in the database.
	FieldFromAddresses = "from_addresses"
	// FieldToAddresses holds the string denoting the to_addresses field in the database.
	FieldToAddresses = "to_addresses"
	// FieldCcAddresses holds the string denoting the cc_addresses field in the database.
	FieldCcAddresses = "cc_addresses"
	// FieldBccAddresses holds the string denoting the bcc_addresses field in the database.
	FieldBccAddresses = "bcc_addresses"
	// FieldSubject holds the string denoting the subject field in the database.
	FieldSubject = "subject"
	// FieldDate holds the string denoting the date field in the database.
	FieldDate = "date"
	// FieldTextBodyExtract holds the string denoting the text_body_extract field in the database.
	FieldTextBodyExtract = "text_body_extract"
	// FieldHTMLBodyExtract holds the string denoting the html_body_extract field in the database.
	FieldHTMLBodyExtract = "html_body_extract"
	// FieldAttachments holds the string denoting the attachments field in the database.
	FieldAttachments = "attachments"
	// FieldSpamScore holds the string denoting the spam_score field in the database.
	FieldSpamScore = "spam_score"
	// FieldAuthResults holds the string denoting the auth_results field in the database.
	FieldAuthResults = "auth_results"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// Table holds the table name of the message in the database.
	Table = "messages"
)

// Columns holds all SQL columns for message fields.
var Columns = []string{
	FieldID,
	FieldTraceID,
	FieldRfcMessageID,
	FieldBlobKey,
	FieldSha256,
	FieldSizeBytes,
	FieldHeaders,
	FieldFromAddresses,
	FieldToAddresses,
	FieldCcAddresses,
	FieldBccAddresses,
	FieldSubject,
	FieldDate,
	FieldTextBodyExtract,
	FieldHTMLBodyExtract,
	FieldAttachments,
	FieldSpamScore,
	FieldAuthResults,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSpamScore holds the default value on creation for the "spam_score" field.
	DefaultSpamScore float64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the Message queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTraceID orders the results by the trace_id field.
func ByTraceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTraceID, opts...).ToFunc()
}

// ByRfcMessageID orders the results by the rfc_message_id field.
func ByRfcMessageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRfcMessageID, opts...).ToFunc()
}

// ByBlobKey orders the results by the blob_key field.
func ByBlobKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBlobKey, opts...).ToFunc()
}

// BySha256 orders the results by the sha256 field.
func BySha256(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSha256, opts...).ToFunc()
}

// BySizeBytes orders the results by the size_bytes field.
func BySizeBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSizeBytes, opts...).ToFunc()
}

// BySubject orders the results by the subject field.
func BySubject(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubject, opts...).ToFunc()
}

// ByDate orders the results by the date field.
func ByDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDate, opts...).ToFunc()
}

// ByTextBodyExtract orders the results by the text_body_extract field.
func ByTextBodyExtract(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTextBodyExtract, opts...).ToFunc()
}

// ByHTMLBodyExtract orders the results by the html_body_extract field.
func ByHTMLBodyExtract(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHTMLBodyExtract, opts...).ToFunc()
}

// BySpamScore orders the results by the spam_score field.
func BySpamScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpamScore, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}
